### ISSUE TITLE
Need appropriate loader to handle this file type

### ISSUE THREAD

**Issue by gemamreza** [YIZHUANG/react-multi-carousel#100]
- Module parse failed: Unexpected character '@' (1:0)

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

> @font-face{font-family:"revicons";fallback:fallback;src:url("./revicons.woff") format('woff'),url("./revicons.ttf") format('ttf')....

and so on

any help? Thank you

**Comment by YIZHUANG** [comment]
Try to Google how to load font in webpack.

**Comment by gemamreza** [comment]
Hi, thank you, it solved

**Comment by sushilbansal** [comment]
Hi @gemamreza , what steps you took to resolve this issue? Please let me know; i am facing the same issues.

**Comment by robinvdv12** [comment]
Same issue here... Please let us know how you fixed it @gemamreza
