### ISSUE TITLE
Using center slide as the current slide in centerMode

### ISSUE THREAD

**Issue by exponentialbit1024** [YIZHUANG/react-multi-carousel#108]
Hi,

I'm using the infinite and centerMode with the carousel, is there a way to make the center slide the current slide, i.e. instead of the first slide being the one on the left (index = 0) can it be set to index = 1 or some other way so that the carousel starts with the center slide.

I try to show 5 slides (the left most and the right most as partials)

Thanks

**Comment by abhinavdalal** [comment]
@exponentialbit1024 if you have the calculations of which is the center slide; then you can just add the bellow goToCenterSlide.. 

if you need help with getting which is the centerSlide in infinite mode then i think there are helper functions for that in `utils/clones`

```
<Carousel ref={(el) => (this.Carousel = el)}>
  <ItemOne />
  <ItemTwo />
</Carousel>

const GoToCenterSlide = (centerSlide) => this.Carousel.goToSlide(centerSlide);
```
