### ISSUE TITLE
Problem with additional left margin while there is only one slide in multiple slide view.

### ISSUE THREAD

**Issue by damianmalinowski** [YIZHUANG/react-multi-carousel#109]
**Describe the bug**
There is an additional left margin while there is only one slide in multiple slide views.

![image](https://user-images.githubusercontent.com/18700400/69966589-01fcd780-1517-11ea-9c40-f4a704b06ed9.png)

**Expected behavior**
Without additional margin on left side, as on below screenshot:
![image](https://user-images.githubusercontent.com/18700400/69966468-c06c2c80-1516-11ea-9412-d3fcd6628979.png)

**Important information**
- I set `partialVisible={true}`
- that margin is `partialVisibilityGutter: 40` size 

**Reproduction**
https://codesandbox.io/s/gracious-kapitsa-2h6hl?fontsize=14&hidenavigation=1&theme=dark

**Comment by abhinavdalal** [comment]
@YIZHUANG will PR: #111 should fix this correct?

**Comment by YIZHUANG** [comment]
It's released in the latest version.
