### ISSUE TITLE
Not working when using bootstrap inside row

### ISSUE THREAD

**Issue by adardesign** [YIZHUANG/react-multi-carousel#110]
**Describe the bug**
Not working when in a bootstrap <div className="row">
**To Reproduce**
1. Go to https://codesandbox.io/s/pedantic-liskov-v4e1j
4. There are 2 examples, one outside a .row (working) then one inside a .row 

**Expected behavior**
It should output the correct DOM regardless  
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 79

**Smartphone (please complete the following information):**

**Additional context**

**Reproduction**
Link to codesandbox.
![Screen Shot 2019-12-04 at 2 11 20 PM](https://user-images.githubusercontent.com/23543/70173046-fc7ec900-169f-11ea-806b-d8821f593293.png)

**Comment by OscarBarrett** [comment]
This is the same issue as in #98

**Comment by YIZHUANG** [comment]
This seems to be a common problem in other Carousel components as well.

**Comment by bartolomeu** [comment]
I've had the same problem... Please add this in the README as "Known Issues" to help others...

**Comment by YIZHUANG** [comment]
Hello, the parent's width needs to be set to 100%
