### ISSUE TITLE
Problem with more 2 active dots on mobile devices

### ISSUE THREAD

**Issue by kgabryje** [YIZHUANG/react-multi-carousel#115]
**Describe the bug**
On mobile device, when you switch slides by clicking a dot and then swiping left or right, 2 dots have an active style.

**To Reproduce**
1. Use a mobile device or Chrome's mobile device toolbar.
2. Click on some dot
3. Swipe left or right
4. Now 2 dots are active

**Expected behavior**
Only a dot corresponding to current slide should be active.

**Screenshots**
![carousel-issue](https://user-images.githubusercontent.com/15073128/70632786-c9a07c00-1c2f-11ea-99cb-fcff3e749320.gif)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 78

**Reproduction**
https://codesandbox.io/s/busy-bell-m6qio

**Comment by abhinavdalal** [comment]
https://codesandbox.io/s/cool-heyrovsky-t65zh
Just added :active to hover button css
```
.react-multi-carousel-dot button:hover:active {
  background: #080808;
}
```
PR: https://github.com/YIZHUANG/react-multi-carousel/pull/118

**Comment by YIZHUANG** [comment]
It's released in the latest version.
