### ISSUE TITLE
Netflix alike partialVisible/centerMode

### ISSUE THREAD

**Issue by bellini666** [YIZHUANG/react-multi-carousel#121]
I would like to be able to change from partialVisible to centerMode as soon as a slide is changed, just like netflix's carousel.

You can see in it that it's first display will be a partialVisible with the latest element partially visible and, after one swipe, it will become a centerMode (with infinity also)

I tried to set centerMode and partialVisible with a boolean state that I would change in the  `afterChange` but I got weird results

**Comment by YIZHUANG** [comment]
This one https://github.com/YIZHUANG/react-multi-carousel/issues/14

**Comment by YIZHUANG** [comment]
Check ```With custom control functionality``` in the storybook example.
