### ISSUE TITLE
CustomLeftArrow and CustomRightArrow not showing up

### ISSUE THREAD

**Issue by tsx-barrytallis** [YIZHUANG/react-multi-carousel#122]
Been following all the examples and I cannot get the custom buttons to show up.  I want them outside to the left and right of the carousel.    I can get the custom group arrows example working but it puts the navigation below the carousel.  I'd like them to look like this < [card] [card] [card] >

```
      <Carousel
        infinite={false}
        responsive={responsive}
       customLeftArrow={<CustomLeftArrow />}
       customRightArrow={<CustomRightArrow />}
        showDots={false}>
```

```
const CustomLeftArrow = ({ previous }) => {
    return (
      <div
        style={{
          textAlign: "center",
          position: "relative"
        }}
      >
        <i className="fal fa-chevron-left" onClick={previous}>TEST</i>
      </div>
  )
};

const CustomRightArrow = ({ next }) => {
  return (
    <div
      style={{
        textAlign: "center",
        position: "relative"
      }}
    >
      <i className="fal fa-chevron-right" onClick={next}>TEST</i>
    </div>
  )
};
```

**Comment by YIZHUANG** [comment]
Its said in the doc that you should set the button group to be positioned absolute. 
Passing renderButtonGroupOutside can also be an option.

**Comment by mehedii-h03** [comment]
I did all this but i am still facing the same issue  I am using react and tailwind CSS

 const CustomLeftArrow = ({ previous }) => {
        return (
            <div

            >
                <i className="fal fa-chevron-left absolute bg-gray-50" onClick={previous}>TEST1</i>
            </div>
        )
    };

    const CustomRightArrow = ({ next }) => {
        return (
            <div

            >
                <i className="fal fa-chevron-right absolute bg-gray-50" onClick={next}>TEST2</i>
            </div>
        )
    };
    
    <Carousel
                    customLeftArrow={<CustomLeftArrow />}
                    customRightArrow={<CustomRightArrow />}
                    responsive={responsive}
                    swipeable={true}
                    draggable={true}
                    infinite={true}
                    autoPlay={false}
                    autoPlaySpeed={1000}
                    arrows={false}>
                    {card}
                    {card}
                    {card}
                    {card}
                    {card}
                    {card}
                </Carousel>
                
                how can I fix the problem?

**Comment by Hyalin-Git** [comment]
> I did all this but i am still facing the same issue I am using react and tailwind CSS
> 
> const CustomLeftArrow = ({ previous }) => { return ( <div
> 
> ```
>         >
>             <i className="fal fa-chevron-left absolute bg-gray-50" onClick={previous}>TEST1</i>
>         </div>
>     )
> };
> 
> const CustomRightArrow = ({ next }) => {
>     return (
>         <div
> 
>         >
>             <i className="fal fa-chevron-right absolute bg-gray-50" onClick={next}>TEST2</i>
>         </div>
>     )
> };
> 
> <Carousel
>                 customLeftArrow={<CustomLeftArrow />}
>                 customRightArrow={<CustomRightArrow />}
>                 responsive={responsive}
>                 swipeable={true}
>                 draggable={true}
>                 infinite={true}
>                 autoPlay={false}
>                 autoPlaySpeed={1000}
>                 arrows={false}>
>                 {card}
>                 {card}
>                 {card}
>                 {card}
>                 {card}
>                 {card}
>             </Carousel>
>             
>             how can I fix the problem?
> ```

probably because of arrows={false}
