### ISSUE TITLE
Carousel goToSlide method is not working.

### ISSUE THREAD

**Issue by Bhagwan96** [YIZHUANG/react-multi-carousel#123]
I am currently using react-multi-carousel V2.5.0, React V16.12.0 and Chrome V79

**Current behaviour:**
I am trying to go to a specific slide using goToSlide method. I called this method in  componentDidUpdate, but it is not working as expected.

**Expected behaviour:**
The Carousel should go to the slide mentioned in goToSlide method.

Code Sandbox link : https://codesandbox.io/s/fancy-water-cbolv

**Comment by YIZHUANG** [comment]
You need to set ref, please follow the documentation.

**Comment by Bhagwan96** [comment]
@YIZHUANG, my bad I forgot to set ref in the above example. But, still it is not working as expected, As per the below example, it should always go to the 5th slide, but it is not the case. 
Here's the sandbox link [https://codesandbox.io/s/objective-fermat-n4445](). Please let me know if I am missing something.
Thanks

**Comment by YIZHUANG** [comment]
@Bhagwan96  This is because in infinite mode after the carousel is mounted, it needs a second re-rendering to create the clones.  In line https://github.com/YIZHUANG/react-multi-carousel/blob/master/src/Carousel.tsx 167, this is call during componentDidMount.
