### ISSUE TITLE
Carousel doesn't render children unless window resize in NextJS 9.2.0.

### ISSUE THREAD

**Issue by AlexanderEerenberg** [YIZHUANG/react-multi-carousel#124]
When upgrading from Next 9.1.6 to Next 9.2.0 the carousel stopped working. After some troubleshooting I found out that when I resize the window the carousel actually does render. Before the resize the unordered list will be empty. 

I created a codesandbox to reproduce a part of the bug as resizing the window will not result in a repaint/rerender there. However, the initial faulty behaviour remains the same, there are no children rendered in the mutli-carousel unordered list.

https://codesandbox.io/s/agitated-dan-k5x4v?fontsize=14&hidenavigation=1&theme=dark

Follow-up: It might be that my SSR implementation of the carousel was done wrong and shouldn't have worked in the first place.. I just checked out the SSR example and updatet to Next 9.2.0 and the example simply works. I will close/update this issue when I find out where I'm failing. My apologies.

**Comment by AlexanderEerenberg** [comment]
What I end up doing to fix this is forcing a rerender by adding the children to state. 

`function TeaserCarousel(props: Props) {
    const [carouselChildren, setCarouselChildren] = useState([]);

    useEffect(() => {
        setCarouselChildren(props.children);
    }, []);

    const responsive = {
        breakPoint: {
            breakpoint: { max: 320, min: 0 },
            items: 1,
            partialVisibilityGutter: 30,
        },
    };
    return (
        <StyledCarousel className={props.customClass ? props.customClass : ''}>
            <Carousel
                customLeftArrow={<CustomArrow direction="left" />}
                customRightArrow={<CustomArrow direction="right" />}
                centerMode={true}
                responsive={props.responsive ? props.responsive : responsive}
                infinite
            >
                {carouselChildren ? carouselChildren : null}
            </Carousel>
        </StyledCarousel>
    );
}`

I'm not too sure if this is an issue that needs to be solved within react-multi-carousel but maybe someone can take a lookt at this.

Cheers!

**Comment by ben-styling** [comment]
Adding the ssr prop with deviceType as in the ssr example also doesn't fix this.

https://codesandbox.io/s/adoring-mccarthy-nqjxx

**Comment by YIZHUANG** [comment]
Yeah, i tried this also in my app, doesn't work with the latest version. Will look into it when have the time.

**Comment by YIZHUANG** [comment]
Works with the latest nextjs 9.2.2.
