### ISSUE TITLE
Partial gutter, for last slide

### ISSUE THREAD

**Issue by jigs1212** [YIZHUANG/react-multi-carousel#13]
In partial right, 
Hide partial gutter for the last slider.

**Comment by YIZHUANG** [comment]
Hi, Can you give more info? Maybe a screenshot and some code snippets?

**Comment by jigs1212** [comment]
[Image](https://www.awesomescreenshot.com/image/3990351/9fef8f76e9b1ef5bdc04ef31495a0e3b)

gutter is added to the last slide, and a space is added there.

**Comment by YIZHUANG** [comment]
@jigs1212 Can you send a full screenshot? You can blur the images.

**Comment by jigs1212** [comment]
[image](https://www.awesomescreenshot.com/image/3990359/5632f011d1dcd55644ffcef4ed2c6781)

there are 2 slides and 2nd slide is active.
in the end of the slide there is space for the third slide partial visiblity. but there is no third slide so it should not come.

**Comment by YIZHUANG** [comment]
@jigs1212  Hi, thank you, i will fix this tonight.

**Comment by jigs1212** [comment]
Thanks

**Comment by YIZHUANG** [comment]
@jigs1212  Problem is fixed now.  https://github.com/YIZHUANG/react-multi-carousel/commit/b16a1d03514efab39229de030860d9ee5f7a010e

Do ```npm install react-multi-carousel --latest```

**Comment by YIZHUANG** [comment]
@jigs1212  Hello, i was testing the fix this morning, just realized that there's still some small width remaining in the last slide, and i made a fix to improve the calculation for it https://github.com/YIZHUANG/react-multi-carousel/commit/2e1dbc08c47a1f9b629021c76d8b467cf6da8cdb   
This time it shouldn't have any problems anymore.

**Comment by jigs1212** [comment]
Thats a great fix.

But for me, my design is like its scrolls from the right edge of the screen, so last slide sticks to the edge.
Is there any way to add some right padding to the last slide?

**Comment by YIZHUANG** [comment]
@jigs1212 You can pass "containerClass" and "itemClass" props to target.

**Comment by jigs1212** [comment]
Thanks.

**Comment by sg-iswift** [comment]
I am using Recat-multi-Carousel but i need partial gutter left and right side both . Could you please help me how can i achieve with this package 
and could you give example how we can send containerClass and ItemClass

**Comment by sg-iswift** [comment]
![image1](https://user-images.githubusercontent.com/101644956/182532646-ae781ce6-275d-4cd9-b5c3-d1c7fc0dd791.PNG)
