### ISSUE TITLE
help --> how to target the center element?

### ISSUE THREAD

**Issue by fallenmel** [YIZHUANG/react-multi-carousel#130]
thanks for this carousel? is there a way that I can target the center element? or the item in the middle?? thanks..

**Comment by fallenmel** [comment]
I use this trick to solve my issue
```
const {
        current: {
          state: { currentSlide, totalItems, slidesToShow },
        },
      } = _ref;

      const _currentSlide = currentSlide == 0 ? totalItems : currentSlide;
      const _offsetCenter = Math.floor(slidesToShow / 2);
      const centerElemIndex = _currentSlide + _offsetCenter;

      centerIndexHandler(centerElemIndex);
```

**Comment by theumar98** [comment]
can you please show your centerIndexHandler function

**Comment by fallenmel** [comment]
```
  const [centerIndex, centerIndexHandler] = useState(0);
```

**Comment by samicodesit** [comment]
> I use this trick to solve my issue
> 
> ```
> const {
>         current: {
>           state: { currentSlide, totalItems, slidesToShow },
>         },
>       } = _ref;
> 
>       const _currentSlide = currentSlide == 0 ? totalItems : currentSlide;
>       const _offsetCenter = Math.floor(slidesToShow / 2);
>       const centerElemIndex = _currentSlide + _offsetCenter;
> 
>       centerIndexHandler(centerElemIndex);
> ```

Can you please show me how you got the `_ref`
in a non-classical component
