### ISSUE TITLE
Missing polyfill method for Internet explorer

### ISSUE THREAD

**Issue by eirikeis** [YIZHUANG/react-multi-carousel#132]
**Describe the bug**
Internet explorer is unable to load the carousel because of a missing polyfill method.

**To Reproduce**
1. Go to 'https://react-multi-carousel.now.sh/' in internet explorer
2. See console error

**Expected behavior**
Expected to see the working carousel

**Screenshots**
![Screenshot 2020-02-17 at 16 04 05](https://user-images.githubusercontent.com/3367849/74665366-dc8b7b80-519f-11ea-8c24-9bd07218423e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser internet explorer
 - Version 11

**Comment by YIZHUANG** [comment]
I guess you would need to add it yourself.
