### ISSUE TITLE
Multiple Rows

### ISSUE THREAD

**Issue by PicardRaphael** [YIZHUANG/react-multi-carousel#134]
Hello,
I want to know if  i can  use  the Multi Rows with your carousel ?
![image](https://user-images.githubusercontent.com/35990535/76238139-b2255f00-622f-11ea-8941-4f1123d47ccb.png)

**Comment by YIZHUANG** [comment]
You should render two catousels and use custom button group combined with ref to navigate.

**Comment by v1ktorbro** [comment]
Hi! Please tell me if there are examples of such an implementation somewhere?
