### ISSUE TITLE
window.resize resets the current slide

### ISSUE THREAD

**Issue by bgracie** [YIZHUANG/react-multi-carousel#135]
**Describe the bug**

Resizing the window resets the current slide

**To Reproduce**

1. go to [the official demo page](https://w3js.com/react-multi-carousel), and the "with infinite mode" example
2. resize the page
3. the current slide will be reset

**Expected behavior**

The current slide should be maintained after the window is resized.  This bug is a big problem on iOS/safari because scrolling will show or hide the URL bar (and therefore resize the window), triggering the current slide to be reset whenever the user scrolls.

**Comment by YIZHUANG** [comment]
Seems release [2.4.1](https://github.com/YIZHUANG/react-multi-carousel/releases/tag/2.4.1) broke this.  Try using a previous version for now.  Will fix this.

**Comment by abhinavdalal** [comment]
@YIZHUANG ill try have a look at this too in a day or 2..

**Comment by abhinavdalal** [comment]
@YIZHUANG i created a pr with the fix.. i have added a test case too.. tested on my local and works as expected

**Comment by YIZHUANG** [comment]
Fixed in the latest version. Thanks @abhinavdalal

**Comment by bgracie** [comment]
> @YIZHUANG i created a pr with the fix.. i have added a test case too.. tested on my local and works as expected

Thanks!
