### ISSUE TITLE
how access carousel functions within another component

### ISSUE THREAD

**Issue by ArouiniLobna** [YIZHUANG/react-multi-carousel#139]
I have a component AA that renders the carousel and the input file.
When i upload a new image, i want to push the carousel to go to the last image when means last slide.

That means i need to access goToSlide function within another function.

i tried using ref, but does not work.

I am using react hooks.

Thank you

**Comment by YIZHUANG** [comment]
Have you tried forwardRef?

**Comment by ArouiniLobna** [comment]
I just found a way yesterday and used Ref but not with useRef hook, i set it using useState. Is working as expected, however it will cost me another render of the component
