### ISSUE TITLE
How to make horizontal scrollbar instead of dot indicator using react-multi-carousel?

### ISSUE THREAD

**Issue by bsultonov** [YIZHUANG/react-multi-carousel#14]
I should have a scrollbar in the bottom of image (like in the picture) instead of ordinary dots. How to make horizontal scrollbar instead of dots using react-multi-carousel? If it is possible, please share a code example, it is urgent. Thanks in advance!

**Comment by YIZHUANG** [comment]
https://github.com/YIZHUANG/react-multi-carousel/blob/master/examples/ssr/components/carousel-with-custom-dots.js

Replace the "const image"  with the scrollbar

**Comment by bsultonov** [comment]
> https://github.com/YIZHUANG/react-multi-carousel/blob/master/examples/ssr/components/carousel-with-custom-dots.js
> 
> Replace the "const image" with the scrollbar component

Sorry, but I did not get your point. Could you show some working example in codesandbox.io or show code snippet?

**Comment by YIZHUANG** [comment]
Can you give me description on the scrollbar that you want to show? Also share your current code snippet so that I can better help.

**Comment by YIZHUANG** [comment]
@bsultonov  Try this https://codesandbox.io/s/ypnk27q1jz?fontsize=14

**Comment by bsultonov** [comment]
> Can you give more description on the scrollbar that you want to show such as the behavior of the scrollbar ? Also share your current code snippet so that I can better help.

I want to make carousel with horizontal black scrollbar in the bottom similar to [this](https://www.rolex.com/ru/watches.html) (there you can see carousel with watches, scroll down a little bit).

**Comment by YIZHUANG** [comment]
@bsultonov  Hi, in this case, you need a few things, first, you need to use a npm package that gives you that scrollbar.  In the scrollbar component, there should be an onChange event. 

```
class MyCarousel extends Component {

render() {
// remember to give your scrollbar a position "absolute" so that it goes under.
  const MyScrollBar = () => {
  <ScrollBar  onChange={(value) => {
  if(this.Carousel) {
  this.Carousel.setState({  transform: -value }) // needs to be negative number here
}
}} />
}
}
return (
<Carousel 
ref={(el) => (this.Carousel = el)}
arrows={false}
showDots={false}
customButtonGroup={<MyScrollBar />}
/>
)
}
```

**Comment by bsultonov** [comment]
> @bsultonov Hi, in this case, you need a few things:
> 
> 1. you need to use a npm package that gives you that scrollbar, or you can make it from scratch.  In the scrollbar component, there should be an onChange event that comes with the scrollbar that gives you the amount of value that the user is scrolling through.
> 2. Give the Carousel a ref reference, this should give you access to the setState function. And attach the setState function to the onChange function that comes with the scrollbar.
> 3. Use the  customButtonGroup props and pass the scrollbar in there like the following.
> 4. Style the scrollbar, give it position "absolute" so that it goes under the Carousel.
> 
> ```
> class MyCarousel extends Component {
> 
> render() {
> // remember to give your scrollbar a position "absolute" so that it goes under.
>   const MyScrollBar = () => {
>   return <ScrollBar  onChange={(value) => {
>                     if(this.Carousel) {
>                     this.Carousel.setState({  transform: -value }) // needs to be negative number here
>                 }
>                )} 
>               />
>              }
> return (
>          <Carousel 
>              ref={(el) => (this.Carousel = el)}
>              arrows={false}
>              showDots={false}
>              customButtonGroup={<MyScrollBar />}
>              />
>          )
>         }
> ```

It seems that it is not so easy as I thought, maybe it is because I have not enough experience in React. I think it would be better to add this feature in the next react-multi-carousel releases, since it could be helpful for others as well. Anyway I like react-multi-carousel for its simplicity and functionality. Keep it up, thanks for trying to help me!

**Comment by YIZHUANG** [comment]
No problem!

**Comment by YIZHUANG** [comment]
@bsultonov You can try like this https://codesandbox.io/s/xov2k18jn4?fontsize=14 . It's just an example, you need to replace the input slider with a better one.

**Comment by bsultonov** [comment]
> @bsultonov You can try like this https://codesandbox.io/s/xov2k18jn4?fontsize=14 . It's just an example, you need to replace the input slider with a better one. Had to admit this is a very complex feature its even hard for me.

Thank you for that. Now I am facing another problem I need to add left padding for my carousel. 


![image](https://user-images.githubusercontent.com/33836521/56950560-39ee0780-6b4f-11e9-9c8e-b1c140f96729.png)

I have tried to use `<Carousel containerClass="carousel-container">...</Carousel>` and in css I have added `.carousel-container {
  padding-left: 10%;
} ` in my css. It works fine and makes padding, but half of the last image becomes invisible (see the picture)

![image](https://user-images.githubusercontent.com/33836521/56951190-9d2c6980-6b50-11e9-95b1-eb4daace5714.png)

![image](https://user-images.githubusercontent.com/33836521/56951230-afa6a300-6b50-11e9-8d26-351632c0a56b.png)

**Comment by YIZHUANG** [comment]
@bsultonov Can you share the code so i can take a better look?

**Comment by bsultonov** [comment]
> @bsultonov Can you share the code so i can take a better look?
 Check it here https://codesandbox.io/s/92nmrq8z0p

**Comment by YIZHUANG** [comment]
```
<div className='wrapper'>
 <Carousel />
</div>
```


```
.image-item {
  padding: 10px 10px 10px 10px;
}
.wrapper {
   padding: 0 10px 0 150px;
}
```

Do something like this, and remove the padding in the ```.carousel-container```

**Comment by bsultonov** [comment]
> ```
> <div className='wrapper'>
>  <Carousel />
> </div>
> ```
> 
> ```
> .image-item {
>   padding: 10px 10px 10px 10px;
> }
> .wrapper {
>    padding: 0 10px 0 150px;
> }
> ```
> 
> Do something like this, and remove the padding in the `.carousel-container`

It makes padding and solves the issue with the last image. However the reason why I used padding was that I wanted it scroll in the behind of my left navigation, otherwise I could use margin.

After your code it became like this
![image](https://user-images.githubusercontent.com/33836521/56954387-17142100-6b58-11e9-9885-3cf383d3dab3.png)

I want it to behave like this
![image](https://user-images.githubusercontent.com/33836521/56954472-49be1980-6b58-11e9-9e74-ecaeca7407f5.png)

**Comment by YIZHUANG** [comment]
Do you mean showing previous and next items partially ? 

Do the following:

```
<Carousel centerMode={true} />
```

And then change the responsive object to the following: 
```
const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 2
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 1
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1
  }
};
```

**Comment by bsultonov** [comment]
> Do you mean showing previous and next items partially ?
> 
> Do the following:
> 
> ```
> <Carousel centerMode={true} />
> ```
> 
> And then change the responsive object to the following:
> 
> ```
> const responsive = {
>   desktop: {
>     breakpoint: { max: 3000, min: 1024 },
>     items: 2
>   },
>   tablet: {
>     breakpoint: { max: 1024, min: 464 },
>     items: 1
>   },
>   mobile: {
>     breakpoint: { max: 464, min: 0 },
>     items: 1
>   }
> };
> ```

It seems that I could not exlain you what I want. Please see carousel  [here](https://www.rolex.com/ru/watches.html). Before scrolling there should be space between left navigation and carousel, but after scrolling carousel should have full width

![image](https://user-images.githubusercontent.com/33836521/56956726-72491200-6b5e-11e9-930f-1c1636099894.png)

**Comment by YIZHUANG** [comment]
something like this https://codesandbox.io/s/0q55qrywvp?fontsize=14 ??  If so, there could be another way to make this better.

**Comment by bsultonov** [comment]
> something like this https://codesandbox.io/s/0q55qrywvp?fontsize=14 ?? If so, there could be another way to make this better.

Yes, exactly. As you can see here the last image become partially invisible

**Comment by bsultonov** [comment]
> something like this https://codesandbox.io/s/0q55qrywvp?fontsize=14 ?? If so, there could be another way to make this better.

If you have time, could you show how to make it better?

**Comment by YIZHUANG** [comment]
Hi, I will check it when I have the time.

**Comment by bsultonov** [comment]
I have used [example](https://codesandbox.io/s/xov2k18jn4?fontsize=14) that you shared with me. And in my styles.css I have just added this 
```
input[type=range]{
  -webkit-appearance: none;
}

input[type=range]::-webkit-slider-runnable-track {
  width: 300px;
  height: 2px;
  background: #ddd;
  border: none;
  border-radius: 3px;
}

input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none;
  border: none;
  height: 5px;
  width: 15%;
  border-radius: 0%;
  background: #000;
  margin-top: -4px;
}

input[type=range]:focus {
  outline: none;
}

input[type=range]:focus::-webkit-slider-runnable-track {
  background: #ccc;
}
```
Thank you very much for that scrollbar. And I will wait for the better solution with padding.

**Comment by YIZHUANG** [comment]
It's very cool scrollbar, thanks!

**Comment by YIZHUANG** [comment]
@bsultonov  try this https://w3js.com/react-multi-carousel/?selectedKind=Carousel&selectedStory=With%20custom%20control%20functionality&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Code: https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/WithScrollbar.js
https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/WithScrollbar.css

In the transform there should be -100 because we need to calculate the padding of the image as well, and there are 5.

**Comment by bsultonov** [comment]
> @bsultonov try this https://w3js.com/react-multi-carousel/?selectedKind=Carousel&selectedStory=With%20custom%20control%20functionality&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
> 
> Code: https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/WithScrollbar.js
> https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/WithScrollbar.css
> 
> In the transform there should be an additional -100px because we need to calculate the padding of the image as well, and there are 5.
> 
> I have published a new version that better work with this. Do: `npm install react-multi-carousel@1.3.18`
> 
> Change log:
> https://github.com/YIZHUANG/react-multi-carousel/releases/tag/1.3.18

That is cool! I hope that it would be helpful for others too. Now, I am so thankful to you, that even I can not explain it in words! You are making great contribution to our society. 

It seems that I need more than 30px padding-left from my navigation, about 100px, but when I change it to 100px in my css file part of the last image wanishes again.

![image](https://user-images.githubusercontent.com/33836521/56991082-46ef1300-6bb0-11e9-8652-7e4200e9bd01.png)

![image](https://user-images.githubusercontent.com/33836521/56991228-97ff0700-6bb0-11e9-92c1-dcf4e89581f6.png)

**Comment by YIZHUANG** [comment]
@bsultonov Hi, thanks, this is very helpful for me too cause i didn't know it can be done like this.

You can change the ```additionalTransfrom``` props. Maybe to something like ```additionalTransfrom={-150}```

**Comment by bsultonov** [comment]
> additionalTransfrom={-150}

I have made it even `additionalTransfrom={-1000}`. Unfortunately, It does not work.

**Comment by YIZHUANG** [comment]
Are you using the latest version?

**Comment by bsultonov** [comment]
> Are you using the latest version?

Now `additionalTransfrom={-150}` works , but it just moves the whole carousel left, so the space between navigation and carousel becomes small. If I increase padding-left again problem with the last image. I don't know it is like dilema

**Comment by YIZHUANG** [comment]
Try this https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/index.stories.js

**Comment by bsultonov** [comment]
> Try this . https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/WithScrollbar.js
> 
> https://w3js.com/react-multi-carousel/?selectedKind=Carousel&selectedStory=With%20custom%20control%20functionality&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Try to scroll using custom scrollbar here https://w3js.com/react-multi-carousel/?selectedKind=Carousel&selectedStory=With%20custom%20control%20functionality&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel It does not scroll smoothely

**Comment by YIZHUANG** [comment]
Check the example and code again, this time should work, couldn't think of any other solutions for now.

**Comment by bsultonov** [comment]
> Check the example and code again, this time should work, couldn't think of any other solutions for now.

Hi, Thank you a lot! Now it works properly.

**Comment by linlapkien** [comment]
hi sir, can i ask, how can I add the scroll bar like the above one. I want to make a carousel that allow user scroll to left or right in touchpad (Macbook)
