### ISSUE TITLE
Get Slide for position

### ISSUE THREAD

**Issue by jamesmarcos2123** [YIZHUANG/react-multi-carousel#143]
Hello, is it possible to get a specific slide by position? 
I dont can use goToSlide. 
keep giving the error Carousel not defined

**Comment by abhinavdalal** [comment]
@jamesmarcos2123 

can you double check if your using ref properly as described in the docs:

```
<Carousel ref={(el) => (this.Carousel = el)} arrows={false} responsive={responsive}>
  <ItemOne />
  <ItemTwo />
</Carousel>
<button onClick={() => {
    const nextSlide = this.Carousel.state.currentSlide + 1;
     // this.Carousel.next()
     // this.Carousel.goToSlide(nextSlide)
  }}>Click me</button>
```

pls close if issue if working after using refs correctly

**Comment by jamesmarcos2123** [comment]
I did exactly as the documentation shows, look 
https://imgur.com/a/28ku6Xx

**Comment by abhinavdalal** [comment]
@jamesmarcos2123 i think in your example you are trying to add a customRightArrow.. 

that can be achieved better via using the prop:
```
const CustomRightArrow = ({ onClick, ...rest }) => {
  const {
    onMove,
    carouselState: { currentSlide, deviceType },
  } = rest;
  // onMove means if dragging or swiping in progress.
  return <button onClick={() => onClick()} />;
};
<Carousel customRightArrow={<CustomRightArrow />} />;
```
also i am not sure but imo using the ref inside the Carousel will not work.. if you see the example of ref the ref is used outside..

**Comment by abhinavdalal** [comment]
@jamesmarcos2123 i dont believe there is any dynamic autoPlaySpeed but you could try to change the props passed on Carousel's state change.. but imo it would not be that performant as it would trigger multiple re-renders..
