### ISSUE TITLE
Methods for disabling arrows while using customButtonGroup

### ISSUE THREAD

**Issue by RicardoPBarbosa** [YIZHUANG/react-multi-carousel#148]
While using a customButtonGroup, it would be great if we could have a boolean inside `carouselState` for example from where we could know if the carousel is at the beginning or the end.

Currently marking the beginning is easy with the `currentSlide === 0` from `carouselState` but the same can't be used to check the end of the carousel at least with multiple `slidesToSlide` for responsiveness as I have.

If I'm missing some way that this is already possible, please let me know. Thank you :)

**Comment by YIZHUANG** [comment]
Try this ````function isInRightEnd({
  currentSlide,
  totalItems,
  slidesToShow
}) {
  return !(currentSlide + slidesToShow < totalItems);
}``
