### ISSUE TITLE
How to determine currently visible child in infinite mode.

### ISSUE THREAD

**Issue by rschick** [YIZHUANG/react-multi-carousel#149]
Is there a way to determine which child is currently visible when in infinite mode?

The afterChange callback seems to get the index of the clone. Is there a way to get the index of the original child that the clone represents?

I want to update UI outside the carousel based on the current slide.

**Comment by YIZHUANG** [comment]
try this https://github.com/YIZHUANG/react-multi-carousel/issues/99
