### ISSUE TITLE
Feature Request : Fade transition

### ISSUE THREAD

**Issue by cb29** [YIZHUANG/react-multi-carousel#151]
Hello,

is there an option to define a fade transition (and not a slide one by one transition). It's usefull for images gallery.

Thanks.

P.S. I tried to use this option customTransition="opacity 1s linear" without success...

**Comment by cb29** [comment]
Hi,
in other carousel system (i.e. Bootstrap), we have this feature. With this option, we get a fadeout transition between slides.

**Comment by YIZHUANG** [comment]
I think this case you would need to disable the animation, and then set opacity 0 to all the Carousel items except for the active one.  You can target the element with some css selectors.

**Comment by YIZHUANG** [comment]
The opacity transition number also need to be passed as a prop as "transitionDuration" beside declearing It in the css.

**Comment by YIZHUANG** [comment]
https://github.com/YIZHUANG/react-multi-carousel/blob/master/src/CarouselItems.tsx

**Comment by arslansajid** [comment]
I am also looking for this feature, is there a prop for this?

**Comment by DawnMD** [comment]
Is there any way to possibly do the fade transition ?

**Comment by michaelroevievictoria** [comment]
Any update on this feature ? :)

**Comment by michaelroevievictoria** [comment]
for future ref: I just create my own css 

```
.fade-in.react-multi-carousel-item--active {
	opacity: 1;
	animation-name: fadeInOpacity;
	animation-iteration-count: 1;
	animation-timing-function: ease-in;
	animation-duration: 2s;
}


@keyframes fadeInOpacity {
	0% {
		opacity: 0;
	}
	100% {
		opacity: 1;
	}
}
```

and added this props

```
additionalTransfrom={0}
transitionDuration={1}
itemClass={`fade-in`}
customTransition="transform 1ms"
```
