### ISSUE TITLE
backwards on infinite mode flick and reset to item 0

### ISSUE THREAD

**Issue by danilockthar** [YIZHUANG/react-multi-carousel#157]
Hi folks. 

Great Carousel component. One of the best out there. Thank you for the time you put it in.

**Describe the bug**
Iam trying to put a 3 items carousel on infinite mode. It works great on forward, but in backward it flicks and reset to item 0, and i dont know why.

**To Reproduce**
1. Go to Carousel component
2. Put on infinite mode with 3 images ( i dont know if length if important)
3. click the backwards arrow till the items start repeating itselfs

**Expected behavior**
Expected to do the normal infinite as when i clicked in forward arrow.

**Screenshots**
![react-carousel](https://user-images.githubusercontent.com/37883725/79074872-381c4600-7cc5-11ea-85c7-884f9bd5454a.gif)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome

**Additional context**
this is my config
const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 2
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 2,
      partialVisibilityGutter: 40
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      partialVisibilityGutter: 30
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      partialVisibilityGutter: 30
    }
  };

<Carousel 
            centerMode={false}
            minimumTouchDrag={80}
            additionalTransfrom={0}
            draggable
            ssr={true} // means to render carousel on server-side.
            infinite
            responsive={responsive}>
.... </Carousel

**Comment by YIZHUANG** [comment]
Length is important, because there isn't enough items to show.

**Comment by danilockthar** [comment]
great!! i will make it non infinite until i have more than five then ! thanks for the quick response and the great component 💯 💯
