### ISSUE TITLE
renderButtonGroupOutside Not working

### ISSUE THREAD

**Issue by rjsnyderdesign** [YIZHUANG/react-multi-carousel#161]
Let me start by saying thank you for all the work on this! It's a great product.

I'm having an issue. I can't get the buttons to render outside of the List container.

```
<Carousel
                            responsive={responsive}
                            arrows
                            additionalTransfrom={0}
                            itemClass={"react-carousel-item"}
                            minimumTouchDrag={80}
                            swipeable
                            partialVisible
                            renderButtonGroupOutside
                        >
```

Am I doing something wrong? 

renderDotsOutside is working.

Any help would be appreciated!! Thank you!

**Comment by YIZHUANG** [comment]
That's no possible that it doesn't render outside, do you have a code sandbox reprodcution?

**Comment by rjsnyderdesign** [comment]
Hi Sorry for the delay.

https://codesandbox.io/s/fervent-rain-332mn?file=/src/App.js

Thank you for any help!

**Comment by YIZHUANG** [comment]
There is no ```customButtonGroup={<ButtonGroup />}``` specified.

**Comment by rjsnyderdesign** [comment]
You are correct. My apologies, I thought you could use one without the other! Thanks again!!!

**Comment by rjsnyderdesign** [comment]
I do have an issue. I'm assuming it's due to my code and not yours.

<ButtonGroup /> is giving me the following error. 

Type '{}' is missing the following properties from type '{ [x: string]: any; next: any; previous: any; }': next, previous

**Comment by n2lose** [comment]
> 
> 
> I do have an issue. I'm assuming it's due to my code and not yours.
> 
> is giving me the following error.
> 
> Type '{}' is missing the following properties from type '{ [x: string]: any; next: any; previous: any; }': next, previous
I got same issue.

**Comment by usahai** [comment]
> > Type '{}' is missing the following properties from type '{ [x: string]: any; next: any; previous: any; }': next, previous
> 
> I got same issue. Its a typescript error and eslint.

Same. Still trying to figure out how to resolve this issue in TS
