### ISSUE TITLE
Buggy scrolling in Firefox

### ISSUE THREAD

**Issue by onair-lena** [YIZHUANG/react-multi-carousel#185]
**Describe the bug**
If carousel has linked items it scrolls with bugs in Firefox desktop. At the same time it scrolls well in desktop Chrome and Opera. 

**To Reproduce**
1. Add links to images in carousel items
2. Scroll carousell in Firefox with mouse click

**Expected behavior**

**Screenshots**

![React-multi-carousel - w3js - Mozilla Firefox 2020-07-16 20-26-02 (1)](https://user-images.githubusercontent.com/47395779/87705135-1b9d1780-c7a6-11ea-89d0-1a5b28bb9a65.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2 

**Reproduction**
https://codesandbox.io/s/react-multi-carousel-playground-7c2kg?file=/components/Simple.js

**Comment by abhinavdalal** [comment]
@onair-lena 

The Carousel component doesn't control the items passed as children which is where this issue is happening.
IMO this is a known firefox issue. My recommendation is to try this solution on your <img>:

https://www.redips.net/firefox/disable-image-dragging/

**Comment by abhinavdalal** [comment]
@YIZHUANG or @onair-lena  pls close this issue..

**Comment by onair-lena** [comment]
> @onair-lena
> 
> The Carousel component doesn't control the items passed as children which is where this issue is happening.
> IMO this is a known firefox issue. My recommendation is to try this solution on your `<img>`:
> 
> https://www.redips.net/firefox/disable-image-dragging/

@abhinavdalal  Thanks for the link, it solved the issue.
