### ISSUE TITLE
Previous arrow disappears before all items return to view

### ISSUE THREAD

**Issue by dw-charterindex** [YIZHUANG/react-multi-carousel#19]
Hi,

When the carousel contains an amount of items not divisible by slidesToSlide, and the end of the carousel is reached by clicking the next arrow, upon clicking on the previous arrow, the previous arrow then disappears before the beginning of the carousel is reached.

For example:

If the carousel contains 10 items, slidesToSlide is set to 3 and the responsive object is set to 3 items, clicking the next arrow 3 times reaches the end of the carousel. Clicking the previous arrow 2 times, the previous arrow then disappears.

```
<MultiCarousel
  ...
  slidesToSlide={3}
  responsive={{
    ...,
    tablet: {
      items: 3
    },
    ...
  }}
  >
  <div /> // * 10
  ...
```

This is a problem when the carousel contains a dynamic number of items.

Please advise whether this is a bug.

Cheers

Darren

**Comment by YIZHUANG** [comment]
Hi, Does this reproduce the problem ? https://codesandbox.io/s/4wko5mw027
Do you mean while the transition is happing the left Carousel arrow disappears? If so then this is expected, because how it works is this:

```
function prev(prevSlide, prevPosition){
  this.setState({
transfrom: prevPosition,
currentSlide: prevSlide
}}
}
<CarouselTrack  style={{
transfrom: translateX(this.state.transfrom),
transition: 'all .5s'
}} />
```
The setState happens before the transition is over. 

Let me know if this is what you mean.

**Comment by dw-charterindex** [comment]
Thank you @YIZHUANG  for your quick reply.

In the example provided, there are 12 items, with 3 items in view, and 3 slidesToSlide. Which works as expected with the next arrow remaining visible until the end of the carousel, and the previous arrow remaining visible until the beginning of the carousel.

The problem I am experiencing is, when the items are not exactly divisible by the items in view or slidesToSlide. For example 10 items, 3 items in view and 3 slidesToSlide. The next arrow works as expected, remaining in view until the end of the carousel, however upon reaching the end of the carousel, clicking the previous arrow, the previous arrow disappears 1 click short of reaching the beginning of the carousel. Like the current slide index is out by 1.

**Comment by YIZHUANG** [comment]
Can you modify the code sandbox to this case?

**Comment by dw-charterindex** [comment]
https://codesandbox.io/s/6znrnxo4mk

Using the previous example, I have reduced the amount of items to 11 (from 12), and it is already setup to show 3 items and 3 slidesToSlide.

However this now displays different behaviour. The next arrow disappears before reaching the end of the carousel.

Click next arrow twice, the arrow disappears, so only 9 items are ever visible to the user. Slides 10 and 11 never slide into view.

**Comment by YIZHUANG** [comment]
Thank you, now I know. And yeah, this is a bug, I will try to fix it by today. Because most of people would choose to use 1 itemToSlide so didn't notice this.

**Comment by dw-charterindex** [comment]
Thanks @YIZHUANG . Much appreciated.

I'm not making use of the partialVisible prop, and the previous behaviour still happens.

**Comment by YIZHUANG** [comment]
Can you make another code sandbox that could reproduce this?

**Comment by dw-charterindex** [comment]
https://codesandbox.io/s/6znrnxo4mk

Removing the partialVisible prop and paritialVisibilityGutter from responsive, demonstrates the previous bug, whereby reaching the end of the carousel, trying to return to the beginning and slides 1 and 2 don't slide back into view and the previous arrow disappears.

**Comment by YIZHUANG** [comment]
@dw-charterindex  The problem should be fixed now https://github.com/YIZHUANG/react-multi-carousel/commit/93e31c284e75335c761cc56eb71e12b38c42f7ef, install the latest version. Let me know if the problem still persist, thanks for the bug report.

**Comment by dw-charterindex** [comment]
Cool, thanks @YIZHUANG for the rapid fix. This is now working correctly.
