### ISSUE TITLE
Drag and drop when the element is a link

### ISSUE THREAD

**Issue by danielpid** [YIZHUANG/react-multi-carousel#195]
First of all, congrats for the work done. This is really a cool library.

**Describe the bug**
I'm opening this as a bug, but maybe it's a misconfiguration on my side, sorry if the latter :)
When the elements inside the carousel are links, when you drag and drop with the cursor inside the same link, you go to the link.

**To Reproduce**
1. Inside the carousel, instead of images, you put links
```
<Carousel
      ssr
      partialVisbile
      deviceType={deviceType}
      itemClass="image-item"
      responsive={responsive}
    >
      {images.slice(0, 5).map((image, index) => {
        return (
          <a
            draggable={false}
            style={{ width: "100%", height: "100%" }}
            href={image}
          >
            {`My link ${index}`}
          </a>
        );
      })}
    </Carousel>
```
2. You drag and drop one of the elements, but the cursor is on the element where you started to drag when you drop
3. As a result, you end up in the link
 
**Expected behavior**
If you are doing drag and drop you shouldn't go to the link

**Reproduction**
https://codesandbox.io/s/react-multi-carousel-playground-forked-z83cx?file=/components/Simple.js

**Comment by raulclaudino** [comment]
I solved the problem like this:

`const ref = useRef(null);
const [canClick, setCanClick] = useState<boolean>(true);

..............

useEffect(() => {
    setTimeout(() => setCanClick(true), 1000);
}, []);

useEffect(() => {
    if (ref.current) {
        var observer = new MutationObserver(function(mutations) {
            mutations.forEach(() => setCanClick(false));
        });
        
        // @ts-ignore
        var target = ref.current.querySelector('.react-multi-carousel-list ul');
        observer.observe(target, { attributes : true, attributeFilter : ['style'] });
    }
}, [ref.current]);

..............

return (
    <ContentSlider ref={ref}>
        <Carousel
            afterChange={() => setCanClick(true)}
        >
            {slides && slides.map((data: any, i: number) => (
                <ContentItems key={i}>
                    <div hidden={canClick} style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 3, background: 'red'}}></div>
                    <a href="#">LINK</a>
                </ContentItems>  
            ))}
        </Carousel>
    </ContentSlider>
);`

**Comment by YIZHUANG** [comment]
Have you looked into the example? https://github.com/YIZHUANG/react-multi-carousel/blob/master/dev/pages/HomePage/HomePage.tsx

**Comment by YIZHUANG** [comment]
https://github.com/YIZHUANG/react-multi-carousel#combine-beforechange-and-nextchange-real-usage

**Comment by eatmoarrice** [comment]
@YIZHUANG If there is no slide change (for example, when you drag it just a bit and it snaps back to the original position), the before/afterChange won't fire and the click will still go through.
