### ISSUE TITLE
List item width is not changing.

### ISSUE THREAD

**Issue by masumluf** [YIZHUANG/react-multi-carousel#204]
Hello, Thanks for this nice work. but I am getting an issue. My slider list item creating an inline style where width is 13px(style="flex: 1 1 auto; position: relative; width: 13px;"). as a result my slide is getting thin. I have attached screen shot in this post. 
![Screenshot from 2020-10-07 21-46-31](https://user-images.githubusercontent.com/4456678/95357122-4dc39e80-08e9-11eb-9edf-e7a834625f37.png)

**Comment by abhinavdalal** [comment]
@masumluf you have not shared any codesandbox so it is very difficult to say where the config is where you config is messed up..
still, start by checking if you have imported: ```import 'react-multi-carousel/lib/styles.css';```
next pass the className you want to give each item in the carosel to the prop: `itemClass`  (make sure className is in the dom)

**Comment by masumluf** [comment]
https://codesandbox.io/s/serene-nightingale-ppo99?file=/src/App.js
My codesandbox link. I tried to add a class on itemClass but it is not working. an automatic inline style taking unnecessary width in my code.

**Comment by abhinavdalal** [comment]
@masumluf sorry.. you need to share a working codesandbox (using the code you are using).. for me to understand what your missing in your config.

**Comment by YIZHUANG** [comment]
Parent is missing 100% width

**Comment by vijaydedikh** [comment]
- [ ] 1. > [`[](url)`](url)
