### ISSUE TITLE
customButtonGroup doesn't hide on responsive breakpoints

### ISSUE THREAD

**Issue by ViacheslavBurlaka** [YIZHUANG/react-multi-carousel#205]
I have props to slider:
```
const sliderProps = {
  infinite: false,
  showDots: false,
  arrows: false,
  renderButtonGroupOutside: true,
  **customButtonGroup: <ButtonGroup />,**
  partialVisible: true,
  keyBoardControl: false,
  containerClass: 'CardsSlider__slider',
  responsive: {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 6,
      slidesToSlide: 6
    },
    tabletHD: {
      breakpoint: { max: 1023, min: 769 },
      items: 4
    },
    tablet: {
      breakpoint: { max: 768, min: 464 },
      items: 3,
      partialVisibilityGutter: 32
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 2,
      slidesToSlide: 2,
      **renderButtonGroupOutside**: false,
      **customButtonGroup: null,**
      partialVisibilityGutter: 32
    }
  }
};
```

**Comment by abhinavdalal** [comment]
@ViacheslavBurlaka i think this is not a feature supported currently. 

I think if you add `removeArrowOnDeviceType="mobile"`; it will work for your case. but currently having different customButtonGroups for each device type is not supported.

**Comment by abhinavdalal** [comment]
@ViacheslavBurlaka my appoligies.. that removeArrowOnDeviceType doesnt work for ButtonGroup.. i think we can create a new 'removeButtonOnDeviceType' prop maybe..

in the meanwhile; you can try a work-around: 
` customButtonGroup= { carouselRef.current.state.deviceType === 'mobile' ? null : <ButtonGroup />`

fyi... carouselRef can be created via useRef and passing it to ref of carousel as:
```js
const carouselRef = useRef();
<Carousel ref={carouselRef} ...otherProps />
```

**Comment by ViacheslavBurlaka** [comment]
Yeah, the last variant is good, I have done it in the same way:)

Next problem for me is swiping on mobiles! It's swipes, but very badly and
just one item for swipe

пт, 9 жовт. 2020 о 07:12 Abhinav Dalal <notifications@github.com> пише:
