### ISSUE TITLE
infinite prop

### ISSUE THREAD

**Issue by sT0pe** [YIZHUANG/react-multi-carousel#21]
```
const responsive = {
    desktop: {
        breakpoint: { max: 3000, min: 1024 },
        items: 4
    },
    tablet: {
        breakpoint: { max: 1024, min: 550 },
        items: 2
    },
    mobile: {
        breakpoint: { max: 550, min: 0 },
        items: 1
    }
};

<Carousel
            responsive={responsive}
             infinite={true}
             containerClass="home-carousel h-full"
             temClass="py-4"
>
      {
            products.map(product => <Product key={product.id} product={product}/>)
       }
</Carousel>
```

If there is only 1 product it somehow duplicate 3 products.
If remove infinite prop than shows only 1 product
Also there is problem with sliding/draging if products less than responsive items

**Comment by YIZHUANG** [comment]
Hi, this is the expected behavior as this is a very rare case that you would have less items to show. You can do a workaround by pre-checking the amount of items first to decide how many to show.
```
const responsive = items => {
  return {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: items < 4 ? items : 4,
    },
    tablet: {
      breakpoint: { max: 1024, min: 550 },
      items: items < 2 ? items : 2,
    },
    mobile: {
      breakpoint: { max: 550, min: 0 },
      items: 1,
    },
  };
};
```
It would be nice to also have some check already in this lib to handle this situation, i will also look into it to see if there's a better handling of this kind of edge cases, any suggestions from you on how the Carousel should behave in case of this?

**Comment by sT0pe** [comment]
Hi, thanks for fast answer! 

`items: items < 4 ? items : 4,`
For example we have long carousel that shows 4 items. If we set such rule it will stratch one item for whole carousel. I son't know if it is possible but whould be nice if carousel will check how many items it has and if items less than responsive than it will automatically disable drag/slide option and maybe hide control buttons also. So if there is only 1 item than show it on left side and 3/4 space empty.

**Comment by YIZHUANG** [comment]
@sT0pe Hi, sounds good, i will find time to make the change.

**Comment by YIZHUANG** [comment]
@sT0pe  Can you modify this code sandbox https://codesandbox.io/embed/2omn67p8kj that could reproduce the problem so that i don't have to  code it from scratch.

**Comment by YIZHUANG** [comment]
@sT0pe  https://github.com/YIZHUANG/react-multi-carousel/commit/62377b01951b160bb16780b11efaa386cbe82776 Let me know if the problem still persists.

**Comment by sT0pe** [comment]
now after loading it compress all items to the left..

**Comment by sT0pe** [comment]
@YIZHUANG https://codesandbox.io/embed/react-multi-carousel-playground-zxgkz?fontsize=14

**Comment by sT0pe** [comment]
@YIZHUANG also if you refresh page in codesandbox you can notice that first it loads big images and after resize. Would be great if it will not show images until it is resized. Same when I update carousel in react it break height and element bounce on the page. Doesn't look good.

**Comment by YIZHUANG** [comment]
@sT0pe  Hi, you need to use the latest version, it seems the version is incorrect here.  About the resizing its because this is an iframe in code sandbox, shouldn't happen in real browser.

**Comment by YIZHUANG** [comment]
@sT0pe  Also if you don't want "first it loads big images and after resize" to happen, just remove "ssr" in the props, like ssr={false}.

**Comment by sT0pe** [comment]
"react-multi-carousel": "^1.4.3"
[http://prntscr.com/nztjya](url)

**Comment by sT0pe** [comment]
@YIZHUANG react-multi-carousel@^1.4.3 installed new version, carousel was not showing
returned to 1.4.2. Carousel shows.

**Comment by YIZHUANG** [comment]
So 1.4.2 works instead of 1.4.3?

**Comment by sT0pe** [comment]
carousel shows on 1.4.2 but with same issues like before..

**Comment by YIZHUANG** [comment]
Are u using ssr? Or pure client side render. Can you provide some codes?

**Comment by sT0pe** [comment]
responsive = items => {
        return {
            desktopBig: {
                breakpoint: { max: 3000, min: 2200 },
                items: items < 5 ? items : 5,
                // items: 5,
            },
            desktop: {
                breakpoint: { max: 2200, min: 1600 },
                items: items < 4 ? items : 4,
                // items: 4,
            },
            desktopSmall: {
                breakpoint: { max: 1600, min: 1024 },
                items: items < 3 ? items : 3,
                // items: 3,
            },
            tablet: {
                breakpoint: { max: 1024, min: 550 },
                items: items < 2 ? items : 2,
                // items: 2,
            },
            mobile: {
                breakpoint: { max: 550, min: 0 },
                items: 1
            }
        }
    };

    render() {
        const {products} = this.props;

        return (
            <div className="py-16 w-full md:w-4/5">
                {products.length > 0 &&
                    <div className="flex items-center relative product-carousel px-12">
                        <Carousel
                            ssr={false}
                            swipeable={swipeable}
                            draggable={draggable}
                            responsive={this.responsive(products.length)}
                            infinite={true}
                            itemClass="py-4"
                            arrows={false}
                            keyBoardControl={false}
                            beforeChange={() => this.setState({ isMoving: true })}
                            afterChange={() => this.setState({ isMoving: false })}
                            ref={(el) => (this.Carousel = el)}
                        >
                            {
                                products.map( product =>
                                    <Product
                                        key={product.id}
                                        product={product}
                                    />
                                )
                            }
                        </Carousel>

                        <button className="btn-left pin-l" onClick={() => this.Carousel.previous()}/>
                        <button className="btn-right pin-r" onClick={() => this.Carousel.next()}/>
                    </div>
                }
            </div>
        );
    }

**Comment by YIZHUANG** [comment]
@sT0pe  https://codesandbox.io/s/nice-saha-jr45j try this one. Also no need to do the hack anymore cause i already added it in the source code. 
```
swipeable={swipeable}
draggable={draggable}
items: items < 5 ? items : 5,
```
Can be removed.

**Comment by YIZHUANG** [comment]
Also there's no need to use "ref" here, you can find the example in here to use the "customButtonGroup" props. https://github.com/YIZHUANG/react-multi-carousel/blob/master/stories/CustomArrows.js

```
const ButtonGroup = ({ previous, next }) => (
<React.Fragment>
  <button className="btn-left pin-l" onClick={() => previous()}/>
  <button className="btn-right pin-r" onClick={() =>next()}/>
</React.Fragment>
)

<Carousel
customButtonGroup={<ButtonGroup />}
>

```

**Comment by sT0pe** [comment]
I didn't use customButtonGroup bcs, I need buttons out of carousel
I copied sandbox code to my project and carousel is not showing as well, could be any issues with localhost?

**Comment by YIZHUANG** [comment]
@sT0pe  It shouldn't be the issues with localhost, any chance you can share the repo?

**Comment by sT0pe** [comment]
@YIZHUANG actually there was an issue with box size, I had flex style there and it was not showing carousel

**Comment by sT0pe** [comment]
seems it works now, will let you know if any bugs. Thanks for help!

**Comment by YIZHUANG** [comment]
NP.
