### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by JxDarkAngel** [YIZHUANG/react-multi-carousel#210]
**Describe the bug**
An error occurs when unmounting the component that contains the Carousel, and this occurs when autoPlay and transitionDuration are enabled

**To Reproduce**
1. Carousel Component Load Start
2. Wait a while in what changes
3. Component replacement by another

**Codigo**

	render() {
		return (
			<WidgetWrapper>
				<Carousel
					showDots={true}
					draggable={false}
					responsive={responsive}
					infinite={true}
					transitionDuration={5000}
					autoPlay={this.state.autoPlay}
					removeArrowOnDeviceType={["tablet", "mobile"]}
					deviceType={this.props.deviceType}
					dotListClass="custom-dot-list-style">
					{TipsComponent.map((e, key) => { return (<div key={key} style={{ height: '100%' }}>{e}</div>) })}
				</Carousel>
			</WidgetWrapper>

		);
	}`
`

**Screenshot**
![image](https://user-images.githubusercontent.com/42661589/98431661-fdbd3080-207c-11eb-96cf-74814bbc5e3b.png)

**Dependences:**
 -  "react": "^16.13.0"
 - "react-multi-carousel": "^2.5.5"

**Comment by Vladis466** [comment]
Bump,
Having this occur with the following settings. Not acting on the item directly but it is occurring as a result of a rerender.


![image](https://user-images.githubusercontent.com/8607517/99958136-baeba000-2d80-11eb-9d08-b3f8ddb16ad8.png)

![image](https://user-images.githubusercontent.com/8607517/99958172-cccd4300-2d80-11eb-8696-214217326016.png)

Dependences:

"react": "^16.13.1"
"react-multi-carousel": "^2.5.5"

**Comment by Vladis466** [comment]
May be related
https://github.com/YIZHUANG/react-multi-carousel/issues/87

**Comment by Vladis466** [comment]
Looks like the fix has been merged, I assume resizing is my issue as well for the time being.
https://github.com/YIZHUANG/react-multi-carousel/pull/198
PR below, however the updates are not on NPM I dont think.

**Comment by Vladis466** [comment]
@YIZHUANG  Thoughts on release for this bugfix?

**Comment by YIZHUANG** [comment]
Released 😀
