### ISSUE TITLE
Free swipe / drag functionality 

### ISSUE THREAD

**Issue by SzymonGalazka** [YIZHUANG/react-multi-carousel#217]
Hello.

Is there a chance to add an option for a 'free swipe/drag' so that by swiping/dragging the carousel, it'll scroll through the items, without stopping on any particular item? 
Just like when you scroll content on a mobile device.
Is it even possible to achieve with the current state of the library, (custom control functionality)?

Thanks in advance.

**Comment by jbelleza29** [comment]
Would like to know as well

**Comment by joeynimu** [comment]
Hey @SzymonGalazka did you figure this out? I'd also like the same functionality. Is this something that's baked in? If not, how difficult is it to add it? I'd make a PR for it if pointed to the right direction/code to mod, let me know.

**Comment by alfidinouhail** [comment]
Hey @YIZHUANG I would like that too, it would be very useful for mobile users. Would also want to know if there is some code guidelines in order to implement that

**Comment by alfidinouhail** [comment]
Hello, @joeynimu @jbelleza29 @SzymonGalazka 
I have figured out a way to implement the smooth scroll - free swipe. Made it on mobile. 
I don't know if it's the right or the wrong way to do it, but here is what I made : 

In your Carousel componenet : 
`<Carousel ssr swipeable={false} />`
Then in your global CSS file, override this CSS class : 
`	.react-multi-carousel-track {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: row;
		position: relative;
		transform-style: preserve-3d;
		-webkit-backface-visibility: hidden;
		backface-visibility: hidden;
		will-change: transform,transition;
		overflow-y: scroll !important;
	}`
What I did is that I have I added this property : `overflow-y: scroll !important;` so it won't depend on item's swipe. 
Hope this helps 
FYI @YIZHUANG

**Comment by YIZHUANG** [comment]
> Hello, @joeynimu @jbelleza29 @SzymonGalazka
> I have figured out a way to implement the smooth scroll - free swipe. I made it on mobile.
> I don't know if it's the right or the wrong way to do it, but here is what I made :
> 
> In your Carousel componenet you have to set the `swipeable` property to `false:`
> `<Carousel ssr swipeable={false} />`
> Then in your global CSS file, override this CSS class :
> ` .react-multi-carousel-track { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: row; position: relative; transform-style: preserve-3d; -webkit-backface-visibility: hidden; backface-visibility: hidden; will-change: transform,transition; overflow-y: scroll !important; } `
> What I did is that I have I added this property : `overflow-y: scroll !important;` so it won't depend on each item's swipe.
> Hope this helps
> FYI @YIZHUANG

Thank you!

**Comment by Benkimeric** [comment]
Great solution @alfidinouhail , also for anyone who wants now to remove the scrollbar that gets introduced, add the following to the css:

```
...
  overflow-y: scroll !important;
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* IE and Edge */
  ::-webkit-scrollbar {
    display: none; /* Chrome, Safari, and Opera */
  }
```
