### ISSUE TITLE
NextJS No Items Populate (Empty Slider)

### ISSUE THREAD

**Issue by GaddMaster** [YIZHUANG/react-multi-carousel#228]
**Describe the bug**
Slider Items do not appear, vanish, poof

**To Reproduce**
Watch this 10 second video [here ](https://www.youtube.com/watch?v=ko1hZlOMYyU) to watch me reproduce on codesandbox link below
https://codesandbox.io/s/charming-yonath-myjvk?file=/pages/index.js
SImple Delete The css and save, works. Then re-add the css and it will work with the style. A refresh = poof, gone

**Expected behavior**
Expect items to appear

**Desktop (please complete the following information):**
 - Windows 10 locally and Vercel Hosting Live
 - Chrome
 - Newest
 
THe issue can be resolved by remove the flex box rules in the css also. These appear to be the specific cause. In the .latest{} rules remove "display:flex" and in the .right{} rule remove the same and no issues. We can replace them with some floating rules and it works fine ?
I suppose why does flex break it ?
 
 Daniel

**Comment by Sangdt** [comment]
It's seem like if container has "display:flex" in their css rules and the carousel isnt being rendered on the server also causing the bugs

**Comment by GaddMaster** [comment]
Yep, 100% flex causing it. I moved to float and its fine !

**Comment by YIZHUANG** [comment]
The parent needs to have a 100% width set

**Comment by Luan4560** [comment]
Thank you that worked 🫡
