### ISSUE TITLE
paritialVisibilityGutter px is not affecting width in centermode

### ISSUE THREAD

**Issue by justin22** [YIZHUANG/react-multi-carousel#23]
In the scenario  **With centerMode, partially visible on both direction**, 
when `paritialVisibilityGutter` is given to handle the width of the partially visible items on both ends, it doesn't update the width. No matter the input, the width stays the default.

Steps to reproduce the behaviour:
Step 1: https://codesandbox.io/embed/cocky-franklin-9fxus
Step 2: Change the paritialVisibilityGutter value

**Expected behaviour**
Based on the `paritialVisibilityGutter` value, width of the partially visible items on both sides should update.

When not in `centerMode` and  given the props, `partialVisbile={true}`, `paritialVisibilityGutter` value is considered for the width of partially visible items.

Also, is there a prop function to reset the carousel items?

**Comment by YIZHUANG** [comment]
Hi, thank you for the issues.

https://github.com/YIZHUANG/react-multi-carousel/blob/master/src/utils/throwError.ts

1.  You are actually not allowed to use paritialVisibilityGutter along with centerMode. Do you mean this? Let me know if i understand this wrong.
2. By reseting the carousel items you mean literally remove them?

**Comment by justin22** [comment]
1. `partialVisbile` with `centerMode` throws error. But when `centerMode={true}` and `partialVisbile={false}`, `paritialVisibilityGutter` is given for the responsive - according to [this example](https://w3js.com/react-multi-carousel/?selectedKind=Carousel&selectedStory=With%20centerMode%2C%20paritially%20visibie%20on%20both%20direction&full=0&addons=1&stories=1&panelRight=0&addonPanel=kadira%2Fjsx%2Fpanel).

2. Not remove them, but update the children dynamically. For instance, If I want to apply some filter to change the children, the carousel needs to reset to 1st slide again.

**Comment by YIZHUANG** [comment]
@justin22 

1. So you mean paritialVisibilityGutter should take into effect even though when partialVisbile is false?
2. Yes you can do it with ref.
```
<Carousel ref={node => this.carouselRef = node } />
<button onClick={() => {
// if not using infinite mode
 this.carouselRef.setState({
currentSlide:0,
transform:0
})
// if using infinite mode
 this.carouselRef. setItemsToShow()
}}>Reset</button>
```

**Comment by justin22** [comment]
1. in `centerMode` we do have partially visible items on both sides. It'd be good if we could control width of the partially visible items. (in this case paritialVisibilityGutter need no to take into effect when partialVisbile is false)
OR
when `partialVisbile={true}`, currently the partial items are either left or right. It'd be good if there's an option to have partially visible items on both sides.

2. Works ! Thank you.

**Comment by YIZHUANG** [comment]
That was my initial idea when implementing this feature but for some reasons I haven't been able to make it work the way you say as it's difficult to calculate the translateX and the amount of width to cut on both sides as well as keeping the amount of items to show on the screen correct and have the balanced spacing between each other. I will try implementing this in the near future again once I find time. But meanwhile you have any idea of implementing it please share or a pr would be great!

**Comment by justin22** [comment]
Sure. I'll give it a try.
