### ISSUE TITLE
Re-calculate width of container on component update

### ISSUE THREAD

**Issue by justin22** [YIZHUANG/react-multi-carousel#24]
**Describe the bug**
When the items in the carousel are updated, i think the container width is not being calculated again.
Suppose if carousel has 10 items initially, and then updated to 3, it creates a lot of empty space in the end, and navigation is possible through this empty space.

**To Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/react-multi-carousel-update-width-h1rcp?fontsize=14l)
2. Click though the buttons to change the count of items in the carousel
3. When count is 5 or 3, use the arrows to navigate
4. See empty white space after the slides

**Expected behavior**
After component is updated, container width should be calculated again.

**Comment by YIZHUANG** [comment]
@justin22  Hi, thank you for the nice reproduce.

This one works. https://codesandbox.io/s/react-multi-carousel-update-width-xd931
It seems the "totalItems" in the Carousel is not updated somehow. I will look into the code why it is not updating automatically.

**Comment by justin22** [comment]
@YIZHUANG  not sure whether this is an issue.
The carousel clones state is updated on the initial render. If the children updated like mentioned above,  clones are not updated. (not sure if this is intended)

**Comment by YIZHUANG** [comment]
@justin22  This is intended cause i believe it's better to handle this in individual cases cause they may various. You could do the following after children update:

```
this.CarouselRef.setClones(); 
```

**Comment by macojaune** [comment]
> @justin22 This is intended cause i believe it's better to handle this in individual cases cause they may various. You could do the following after children update:
> 
> ```
> this.CarouselRef.setClones(); 
> ```

Hi, is this still available ?
