### ISSUE TITLE
CustomDot component's show react key warning.

### ISSUE THREAD

**Issue by neamatmim** [YIZHUANG/react-multi-carousel#25]
**Description**
CustomDot component's show react key warning.
note: Keys should be given to the elements inside the array to give the elements a stable identity:

**Expected behavior**
No Warning
**Screenshots**
<img width="831" alt="Screenshot 2019-06-18 at 4 40 44 PM" src="https://user-images.githubusercontent.com/37859935/59677304-515e7e00-91eb-11e9-9317-461eaae8e39c.png">

**Comment by YIZHUANG** [comment]
I have now published a new version.
