### ISSUE TITLE
Autoplay on hover

### ISSUE THREAD

**Issue by prakhar-parashar-au7** [YIZHUANG/react-multi-carousel#253]
Autoplay on slider doesn't work( is set to false by default) when mouse is hovered over the slider, react-responsive-carousel, and other slider give  props like onHoverStop which can be set to false, is there anything like this in react-multi-carousel, I want the slider to keep autoplaying even when user hovers over it

**Comment by nev1d** [comment]
fixed this on this pr - https://github.com/YIZHUANG/react-multi-carousel/pull/263
