### ISSUE TITLE
carousel messes up style of everything else in mobile. (item-width explodes)

### ISSUE THREAD

**Issue by Mudl** [YIZHUANG/react-multi-carousel#259]
Everything works fine in desktop size, but as soon as I reduce the screen size to mobile, using chrome dev tools, everything breaks. The carousel just puts the images right next to each other so that the screen width explodes and therefore it messes up everything else as well. 

the width just increases until it reaches this point.
`<li data-index="0" aria-hidden="false" class="react-multi-carousel-item react-multi-carousel-item--active pl-3 pr-3" style="flex: 1 1 auto; position: relative; width: 1.67771e+07px;">`

used just one breakpoint in "responsive" since I want all of them look the same anyways. 
and a custom component as an item, but result is the same with just plain old img.
carousel itself is within a flex block.

I have no idea if I'm doing something wrong, or if this is a bug. Please advise.

**Comment by Toby222** [comment]
Did you find a solution to this? Facing the same issue

**Comment by Axel-KIRK** [comment]
Same here, I just add some image instead of the list and BOUM.

**Comment by YusufTurhan17** [comment]
By giving maxwidth 100vw to the container, you can solve the problem.
