### ISSUE TITLE
Carousel failed to load items sometimes (containerWidth, itemWidth issue)

### ISSUE THREAD

**Issue by codex49** [YIZHUANG/react-multi-carousel#266]
Sometimes the Carousel failed to load items
When I check the state in react dev
I got 0 in containerWidth and itemWidth, when I change the value of containerWidth to 100
The items loaded, the Carousel works well the the value of containerWidth  changes to 1140 and itemWidth to 228

![slider](https://user-images.githubusercontent.com/11504046/121390834-ab5f2d80-c945-11eb-8dc7-58e33be5ff6c.PNG)

HTML code when the problem is happen
`<div class="react-multi-carousel-list carouselContainer"><ul class="react-multi-carousel-track " style="transition: none 0s ease 0s; overflow: unset; transform: translate3d(0px, 0px, 0px);"></ul></div>`

**Comment by ankit-kumar-jat** [comment]
i am having same issue if you resolved this issue please comment here

**Comment by abhinavdalal** [comment]
@ankit-kumar-jat can you confirm that css file is imported via:

`import 'react-multi-carousel/lib/styles.css';`

**Comment by zmeyer44** [comment]
Same issue here

**Comment by abhinavdalal** [comment]
can someone please share a codesandbox or a js fiddle replicating the issue

**Comment by ankit-kumar-jat** [comment]
Please check css that you applied and also check css for parent component in which you are using carousel

**Comment by alicerocheman** [comment]
same issue, if I log my slider's children, it logs children properly, but in the inspector the UL is empty.
fragments seem to be wrongly interpreted as well, might be related.

**Comment by denFete** [comment]
Had the same issue, solved by adding:
`.react-multi-carousel-list {
    display: flex;
    align-items: center;
    overflow: hidden;
    position: relative;
    **width: 100%;**
}`

**Comment by Tankiac** [comment]
I had the same issue and I fixed it by giving the parent div a min-width.

**Comment by YIZHUANG** [comment]
The parent needs to have a width of 100%
