### ISSUE TITLE
Is there any way to use box-shadow properly?

### ISSUE THREAD

**Issue by ncesar** [YIZHUANG/react-multi-carousel#271]
**Describe the bug**
I realized that using box-shadow in a component makes the slider looks weird.

**To Reproduce**
1. Create a slider
2. Add an item that has a box-shadow
3. It will have a buggy shadow

**Expected behavior**
Shadows to be properly applied to children

**Screenshots**
![image](https://user-images.githubusercontent.com/29064514/124517752-27208e80-ddbb-11eb-8b14-48b76b7a90fb.png)

**Additional context**

**Reproduction**
https://codesandbox.io/s/angry-dust-uz1by

**Comment by jayeshnathwani** [comment]
In you example Box-shadow is working but only left and right as there is no space at top and bottom. Add margin and it should work. 

After adding margin:10px;

![image](https://user-images.githubusercontent.com/12597505/125055779-7ad2f680-e09f-11eb-924e-684dfd26e3a9.png)

Note: you may want to verify does margin affect any other place like paging, i havent verified that.
