### ISSUE TITLE
Clicking between elements and then dragging will randomly highlight/flicker the elements

### ISSUE THREAD

**Issue by Torniojaws** [YIZHUANG/react-multi-carousel#274]
**Describe the bug**

Random blue highlight / selection of the elements in the carousel.

**To Reproduce**

1. Open the project example on Firefox: https://react-multi-carousel.vercel.app
2. Go to the second example row
3. Left-click and hold between two images
4. Drag mouse left or right
5. It will randomly flash on/off a blue selection overlay.

**Expected behavior**

Should not flicker.

**Screenshots**

![flicker](https://user-images.githubusercontent.com/5442750/128068849-178fa0ee-a155-4819-b021-c39a41828de1.gif)

**Desktop (please complete the following information):**

 - OS: Windows & Linux
 - Browser: Firefox
 - Version: 90+

**Comment by Torniojaws** [comment]
It appears it can be avoided by some CSS. It would be good if this could be included into `react-multi-carousel` "natively":

```
<div className="disableSelection">
  <Carousel>
    // some stuff
  </Carousel>
</div>
```
With this CSS:

```
div.disableSelection {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

**Comment by YIZHUANG** [comment]
Thank you!
