### ISSUE TITLE
CarouselItems.js:1 Uncaught TypeError: Cannot read property 'ariaLabel' of undefined

### ISSUE THREAD

**Issue by nav-wooliesx** [YIZHUANG/react-multi-carousel#277]
![Screen Shot 2021-08-18 at 9 16 38 pm](https://user-images.githubusercontent.com/82793189/129888960-2eab78f6-8c49-44cd-82d7-369f39d98b8b.png)

**Comment by thuhangnth** [comment]
Hi @nav-wooliesx , How did you manage to solve this error? 
I'm on version 2.8.4 and encountering the same error.
