### ISSUE TITLE
Documentation site is down with 500 error

### ISSUE THREAD

**Issue by Sammii** [YIZHUANG/react-multi-carousel#279]
https://w3js.com/react-multi-carousel is returning a 500 Server Error and cannot be accessed.

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

**Comment by abhinavdalal** [comment]
@YIZHUANG can you look into this.. seems like an issue on the host server..

**Comment by YIZHUANG** [comment]
Thanks, i am looking into fixing it

**Comment by YIZHUANG** [comment]
It's fixed now
