### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dmitriy-sokolyanskiy** [YIZHUANG/react-multi-carousel#280]
**Describe the bug**
After `npm install react-multi-carousel --save`
it doesn't create node_modules/react-multi-carousel/lib  directory
and `import 'react-multi-carousel/lib/styles.css';`  throws an error
`Module not found: Can't resolve 'react-multi-carousel/lib/styles.css'`

**To Reproduce**
1. npx create-next-app --use-npm carousel
2. npm install react-multi-carousel --save
3. in pages/index.js
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
4. See an error: Module not found: Can't resolve 'react-multi-carousel/lib/styles.css'

**Comment by Florian-crg** [comment]
Same problem

**Comment by iuzn** [comment]
Bu sürümü kullanmayı dene `"react-multi-carousel": "2.4.1"`

**Comment by iuzn** [comment]
You can try using this version: `"react-multi-carousel": "2.4.1"`

**Comment by TimNZ** [comment]
This is why I tend to lock dependencies to a specific version and manually update

**Comment by OscarBarrett** [comment]
@YIZHUANG FYI

**Comment by YIZHUANG** [comment]
My bad, should be fixed now if you install the latest version
