### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-multi-carousel/lib/styles.css'

### ISSUE THREAD

**Issue by rogereiddir** [YIZHUANG/react-multi-carousel#282]
this Error accurs when tryiing to deploy to vercel or heroku can any one help me with this?

.babelrc
```
{
    "presets": ["next/babel"],
    "plugins": [["styled-components", { "ssr": true }]]
}

```

next.config.js

```
const withPlugins = require('next-compose-plugins');
const withOptimizedImages = require('next-optimized-images');
// next.js configuration
const nextConfig = {
  async redirects() {
    return [
      {
        source: '/',
        destination: '/home',
        permanent: false,
      },
    ];
  },
};

module.exports = withPlugins([withOptimizedImages] , nextConfig);
```

**Comment by umanga907** [comment]
do not use the newest version. I just had the same issue. On the new version there is no lib folder nor there is any styles.css file.
you can change it to older version and run npm install or yarn install again. 
@rogereiddir please look into this issue, its breaking a lot of build and the documentation has not been updated yet.

**Comment by YIZHUANG** [comment]
Should work now
