### ISSUE TITLE
Scrolling to the left is not working as expected

### ISSUE THREAD

**Issue by donotcodeit** [YIZHUANG/react-multi-carousel#296]
To reproduce we need to have 4 slides in total, and 3 to be shown. Then, after scrolling to the left 4 times, we will see that slides will be in incorrect order.

There is reproducible demo: https://github.com/donotcodeit/react-multi-carousel-scroll-left
You can run it by `dotnet run` or by `F5` in VS Code. `./ClientApp` folder contains the demo.

Actually, I've already found the problem. The line that contains incorrect calculation: https://github.com/YIZHUANG/react-multi-carousel/blob/18479e77f21fffde5affe1ac4b18e05f3a5dcd9d/src/utils/clones.ts#L166 
To fix it we need to set `nextSlide` value to the first slide of the third clones sequence. So `totalItems / 3` will fix the problem. I can make a PR if it is correct way.

Also, it would be great, if this fix will be released as soon as possible. So I can provide any help you need.

**Comment by donotcodeit** [comment]
@YIZHUANG any updates on this?

**Comment by ak-pdeshaies** [comment]
[@YIZHUANG](https://github.com/YIZHUANG) I would like to get this fixed as well :-) 
Do you have any idea if and when you will include @[donotcodeit](https://github.com/donotcodeit) 's fix?
I've tested his solution in my situation (6 items with 4 items shown at a time) and his solution works for me as well.

BTW, Thanks for a great library :-)

**Comment by YIZHUANG** [comment]
@donotcodeit can you make the PR? I will take a look

**Comment by ak-pdeshaies** [comment]
I've done a PR for this issue.

ALL credits should go to Pavel Mikheev

Thanks

**Comment by YIZHUANG** [comment]
It's fix now
