### ISSUE TITLE
partialVisibilityGutter did not work for tablet view (gap issue between items)

### ISSUE THREAD

**Issue by UthpalaP** [YIZHUANG/react-multi-carousel#300]
I have used the following responsive configurations for desktop, tablet and mobile views.
 ![image](https://user-images.githubusercontent.com/86960989/138452679-b9ca36a3-0596-475c-bbf1-23314a8face9.png)

The above configuration works for desktop and mobile view, BUT not for tablet view. With the varying screen sizes the gap between items very drastically.  When implementing items in the carousel I have used a fixed width.

Can anyone recommend a good responsive configuration values or is there any way to keep the gap fixed with varying screen sizes.

**Comment by YIZHUANG** [comment]
Yeah, seems like the values needs tweaking for tablet, instead of 120, what other values have you tried?

**Comment by azipare** [comment]
@YIZHUANG Any solution for above issue?
