### ISSUE TITLE
[Question] partialVisbile props name

### ISSUE THREAD

**Issue by MuhammadAlbab** [YIZHUANG/react-multi-carousel#302]
I kept getting this warning when using partialVisbile props:  "Please correct props name: "partialVisible" as old typo will be removed in future versions!", what is the correct name for this props? can't find it in the docs. thankyou

**Comment by abhinavdalal** [comment]
`partialVisibile`

there is an extra 'i' after s

**Comment by MuhammadAlbab** [comment]
lmao, i'm so sorry, my bad. my stupid autocomplete messed up haha. thankyou
