### ISSUE TITLE
Infinite mode renders wrong index items

### ISSUE THREAD

**Issue by bipinstha7** [YIZHUANG/react-multi-carousel#309]
Hi, 
First thank you for this awesome package and the contribution.

As this packages clones the original item when `infinite: true`, the original index values changes. Original index of 0 might changes to 3/4/5 or some other values.
We can get the original index using `getOriginalCounterPart` but my case is different here.
We are rendering items based on the ordering (same as index). When it passes through clones the item orders mismatches but we need the exact order as before. 

Can you please help me to retain the original order of the items in infinite mode? Everything works good on finite mode but breaks on infinite mode.

**Comment by abhinavdalal** [comment]
clones should not change order.. clones uses the same array as original and only appends and prepends to it..  because infinite mode is rotational it may seem its starting from some mid-point in the array.. but order should be maintained.. 

if you have a code sandbox created where you can replicate then maybe it will be possible to investigate what is going on in your case.. i doubt clones would be the issue though..

**Comment by bipinstha7** [comment]
> clones should not change order.. clones uses the same array as original and only appends and prepends to it.. because infinite mode is rotational it may seem its starting from some mid-point in the array.. but order should be maintained

Thank you for the response and yes as you have mentioned, the array has the same order as the original one but starting from some mid-point in the array.
How do I start the infinite mode array from the start? I need to start from the order 1. Can you please help me to get it from start?

**Comment by abhinavdalal** [comment]
https://github.com/YIZHUANG/react-multi-carousel#using-ref
call goToSlide() in the useEffect of parent component.. 

please close this issue.. thanks..

**Comment by bipinstha7** [comment]
> @bipinstha7 can you share how you resolved this. If I try the goToSlide it starts behaving like autoplay.

Hi @irahulranjan , _goToSlide_ didn't work for me as well. I haven't resolved this issue yet, just rendering items without proper ordering. I am planning to revert back to **infinite: false** mode but it also has the UI problem.

**Comment by ducndt** [comment]
Hi @bipinstha7 , does your problem resolve, i'm now struggling with same problem

**Comment by bipinstha7** [comment]
> Hi @bipinstha7 , does your problem resolve, i'm now struggling with same problem

Hello @ducndt, I couldn't resolve the issue so I moved back to the **infinite: false** mode with the prev and next button/icon.

**Comment by ducndt** [comment]
thanks you, have a good day
