### ISSUE TITLE
Is it possible to do it vertically?

### ISSUE THREAD

**Issue by tiavina-mika** [YIZHUANG/react-multi-carousel#313]
**Prerequisite**

Before you submit a feature request or report a bug to be fixed, make sure you have stared this repository. A [donation](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=GJSPRG9RKSJLQ&source=url) is also welcomed

**Describe the bug**
The direction should be vertically, to top to bottom

**Comment by YIZHUANG** [comment]
Hello,

It's possible but I think that will include a lot of changes and will increase the bundle size a lot too...
