### ISSUE TITLE
autoplay turns on as soon as one has interacted with the slider.

### ISSUE THREAD

**Issue by zehawki** [YIZHUANG/react-multi-carousel#326]
**Describe the bug**
Issue with AutoPlay. 
If autoplay prop has NOT been set, or even explicitly set to false, autoplay turns on as soon as one has interacted with the slider.

However setting `shouldResetAutoplay={false}` _turns this behavior off._
Its extremely unintuitive that "automatic" autoplay can be turned off by setting `shouldResetAutoplay={false}`. I discovered this only with various trials.

**Expected behavior**
When autoPlay is off, it should be off, irrespective of interactions with the slider.

**Version**
v2.8.0

**Comment by jtas01** [comment]
Same is happening with me too.

**Comment by zehawki** [comment]
Actually now I'm quite puzzled as to what this prop is supposed to do.

With `autoPlay` and `shouldResetAutoplay` both set to true, I expected that the autoplay will STOP (ie get reset as the prop name says) as soon as one has interacted with the slider. But setting `shouldResetAutoplay` to true or false seems to be having no effect.

**Comment by hackntest** [comment]
Having the same issue

**Comment by djordjejanjic** [comment]
Did anyone solve this? I have trouble with this bug also

**Comment by alitursucular** [comment]
Definitely not a solution, but a workaround I ended up with is to set `autoPlaySpeed={10000000}`.

**Comment by jtas01** [comment]
> Definitely not a solution, but a workaround I ended up with is to set `autoPlaySpeed={10000000}`.

This made me lol.... nice workaround. But definitely need a real solution soon.

**Comment by djordjejanjic** [comment]
I just tried with shouldResetAutoplay = false and autoplay = false. It works!

**Comment by trinhtuan2801** [comment]
> shouldResetAutoplay

it works for me <3

**Comment by trinhtuan2801** [comment]
> 



> shouldResetAutoplay = false and autoplay = false

it works for me 💯

**Comment by sandeepDevJs** [comment]
> I just tried with shouldResetAutoplay = false and autoplay = false. It works!

This worked for me. thanks dude.

**Comment by zehawki** [comment]
>I just tried with shouldResetAutoplay = false and autoplay = false. It works! 

@djordjejanjic Isnt that exactly what I said in the first post? :-)

**Comment by djaffer** [comment]
same issue. Just saved the hassle.

> I just tried with shouldResetAutoplay = false and autoplay = false. It works!

thank you! @djordjejanjic

**Comment by YIZHUANG** [comment]
This was a bug caused by one of the PRs, should be fixed now in the latest version

**Comment by YIZHUANG** [comment]
This was a bug caused by one of the PRs, should be fixed now in the latest version
