### ISSUE TITLE
Suggestion: Add option for autoplay to rewind the carousel and start over

### ISSUE THREAD

**Issue by MaSchVam** [YIZHUANG/react-multi-carousel#330]
It looks as if the amount of DOM elements created by enabling 'Infinite' mode could scale in an undesirable way. 

This can result in a lot of DOM elements in certain scenarios, where you are interested in just having a permanently sliding carousel. Could a decent trade-off to having infinite mode enabled, perhaps be to have an option that works in conjunction with `autoPlay` and a non-infinite carousel, that simply rewinds the carousel and begins its sliding from beginning to end again when finished?

**Comment by abhinavdalal** [comment]
related to #74

**Comment by abhinavdalal** [comment]
@MaSchVam the logic rotates between 3 * total number of slides at max.. so its not exponential at all.. but yes performance issues can creep in at large number of slides.. i was hoping to virtualize it using react-virtualized or some such tool..

**Comment by MaSchVam** [comment]
> @MaSchVam the logic rotates between 3 * total number of slides at max.. so its not exponential at all

Yes, you are right - I updated my post. I think what I was trying to say, is that the performance implications of infinite mode are somewhat unclear and hard to calculate. Especially if you are dynamically generating carousels from a data source somewhere else.

Virtualizing it is definitely an idea - but a lower fidelity solution could also be to simply reset the transform on the slide track at the end of a non-infinite carousel, so that the sliding process can be started over. A `rewind={true/false}` prop, perhaps?

Depends on the use-case though. I understand why you'd always want to preserve being able to slide infinitely, bilaterally.

**Comment by YIZHUANG** [comment]
https://github.com/YIZHUANG/react-multi-carousel/blob/master/src/utils/clones.ts#L88 for the clone logic, cloning the items 3 times happen only on small list (according to my old comment)
The rewinding to beginning for non-infinite carousel would work, would you be able to contribute to open a PR?

**Comment by MaSchVam** [comment]
Hello @YIZHUANG,

I had a look at it today, and have opened #334 as a proposal towards what i suggested here.
