### ISSUE TITLE
Render custom button group above the carousel

### ISSUE THREAD

**Issue by Luks3110** [YIZHUANG/react-multi-carousel#401]
When I pass the renderButtonGroupOutside along with a customButtonGroup, I need to button group to be rendered above the carousel, not below, Is there any workaround, since there is no prop for the position of the button group?

```
 <Carousel
      arrows={false}
      swipeable={false}
      responsive={breakpoints}
      customButtonGroup={<ButtonGroup />}
      renderButtonGroupOutside
      ssr
    >
     //...
    </Carousel>
```

**Comment by Luks3110** [comment]
Solved by using ref

**Comment by bhaveshdaswani93** [comment]
I also facing the similar issue, may I know how did you solve it? like how are you using ref?
