### ISSUE TITLE
no re-render of child when in infinite mode 

### ISSUE THREAD

**Issue by waxyfoxy** [YIZHUANG/react-multi-carousel#48]
**Describe the bug**
In infinite mode, children do not re-render when state changes. I use a visual marker to show which slide is currently in focus, in infinite mode, when changing the focused slide, the visual marker stays on the slide that was previously focused. When I refresh, the re-render happens and the visual marker is correct. Is there a way to force the re-render ? FYI when not in infinite mode, the exact same code works perfectly.

**To Reproduce**

here is the code : the <SwitcherBlock/> component is just a presentational componant that you can replace with a simple div. "current" is the id of the id of the item i am presenting on the rest of my page and i want my carousel on the top to show the visual marker showing that it is the active item. 

        <Carousel
          ref={carouselEl}
          swipeable={true}
          draggable={true}
          showDots={false}
          arrows
          customLeftArrow={<Arrow />}
          customRightArrow={<Arrow />}
          responsive={responsive}
          ssr={false} 
          infinite={false}
          additionalTransfrom={-1}
          autoPlay={false}
          keyBoardControl
          minimumTouchDrag={80}
          transitionDuration={10}
          containerClass="carousel-container"
          dotListClass="custom-dot-list-style"
          itemClass="carousel-item-padding-40-px"
          focusOnSelect={true}
        >
          {campaigns.items.map((campaign, index) => {
            return (
              <SwitcherBlock
                key={campaign.id}
                isActive={current === campaign.id}
                campaign={campaign}
              />
            )
          })}
        </Carousel>

**Expected behavior**
same as when not in infinite mode

**Desktop (please complete the following information):**
 - Browser : chrome

**Comment by YIZHUANG** [comment]
Hi, i understand this issue.

Can you clone the repo and then go to this branch https://github.com/YIZHUANG/react-multi-carousel/tree/rerender-clones-experimental.

1. Go to the root dir
2. git checkout rerender-clones-experimental
3. npm install
4. npm run build
5. yarn link
6. Go to your own project's dir
7. yarn link react-multi-carousel

Let me know if this fixes this problem.

**Comment by waxyfoxy** [comment]
Hi, 
Thank you for your quick answer ! 
Unfortunately this did not solve my problem, behaviour is still the same in infinite mode...

**Comment by waxyfoxy** [comment]
Hello, the fix works fine, when do you think that you will merge this branch into your main repo ?

**Comment by YIZHUANG** [comment]
@waxyfoxy  So with this, it re-renders the item?

**Comment by waxyfoxy** [comment]
yes it does !

**Comment by YIZHUANG** [comment]
Do ```npm install react-multi-carousel@next --save```, this is a temporarily version before i have time to make sure this version doesn't break the existing stuff.

**Comment by YIZHUANG** [comment]
This is now available in 2.2.2
