### ISSUE TITLE
changing indexes when in infinite mode

### ISSUE THREAD

**Issue by waxyfoxy** [YIZHUANG/react-multi-carousel#49]
**Describe the bug**
I use a useEffect to mount the carousel on a particular slide. when in infinite mode, the index returned by the carousel do not match the item i want to show. Once again when not in infinite mode, it works perfectly. 

**To Reproduce**
  useEffect(() => {
    if (carouselEl.current && campaigns) {
      const index = carouselEl.current.state.clones.findIndex(
        clone => clone.props.campaign.id === current,
      )
      carouselEl.current.goToSlide(index)
    }
  }, [carouselEl.current])

**Expected behavior**
i want to be able to open the carousel on a specific slide

**Comment by YIZHUANG** [comment]
This is because during the "clone" process, the original index has been changed, it's not the same anymore.

There is a helper function that can get the index back after the "clone" process.

try
```
import {getOriginalCounterPart} from 'react-multi-carousel/lib/utils';

useEffect(() => {
if (carouselEl.current && campaigns) {

const newIndex = getOriginalCounterPart(current, carouselEl.current.state, React.children.toArray(carouselEl.current.props.children)); // get the new index back after clone

const index = carouselEl.current.state.clones.findIndex(
clone => clone.props.campaign.id === newIndex,
)
carouselEl.current.goToSlide(index)
}
}, [carouselEl.current])
```

**Comment by waxyfoxy** [comment]
Hi, I implemented this solution but I slightly changed the code (see below) and it works fine ! 
Moreover, by adding my "current" variable in the dependencies of the useEffect it calls the getOriginalCounterPart function every time I click a new slide thus forcing a re-render which actually also solved my previous issue (https://github.com/YIZHUANG/react-multi-carousel/issues/48)

Thanks a lot !

  useEffect(() => {
    if (carouselEl.current && campaigns) {
    const index = campaigns.items.findIndex(
            campaign => campaign.id === current,
          )
    const newIndex = getOriginalCounterPart(index, carouselEl.current.state, carouselEl.current.props.children) // get the new index back after clone
    
    carouselEl.current.goToSlide(newIndex)
    }
    }, [carouselEl.current, current])

**Comment by waxyfoxy** [comment]
Careful, if you refresh quickly, the carousel might not have time to generate the clones hence the useEffect won't work. To fix it you can use a setTimeout with a 0 delay in order to wait for the next JS event loop and be sure that the clones exist

**Comment by YIZHUANG** [comment]
@waxyfoxy  The setTimeout should be equivalent to what you pass to the carousel. 

For example:
```
<Carousel transitionDuration={500}  /> 
```
Then it should be 500.
Default is 400 if not specified.

**Comment by chocobuckle** [comment]
I'm having the same issue as @waxyfoxy, but I'm wondering how I can use getOriginalCounterPart if not using React Hooks? Put it in beforeChange? There's no documentation about how to use this helper.

**Comment by YIZHUANG** [comment]
@chocobuckle This has nothing to do with hooks, you can do this in "componentDidMount" and "componentDidUpdate" to replace "useEffect".   "getOriginalCounterPart" is an internal method, i can not document it as this is not a common use case that i am not able to anticipate.

**Comment by chocobuckle** [comment]
@YIZHUANG I'm just wondering what its arguments are? I see in your example you have 'current' - but's it's not declared anywhere. Is that the current index? Any help would be appreciated. :)

**Comment by YIZHUANG** [comment]
current is the index of the slide. For example, I wanted to know the actual index of a slide after the clone process, and the index is 1 currently, then current is 1.

**Comment by chocobuckle** [comment]
Ok, and elsewhere current is a property on the ref, right? I'm just getting mixed up between the two different values for current.

**Comment by YIZHUANG** [comment]
Yes, sorry about that. Infinite mode in Carousel is very complicated, needs some digging.

**Comment by chocobuckle** [comment]
Thanks a lot for that clarification. One final question please - is the clone process triggered automatically when in infinite mode? Or is that something I have to call manually? Coz right now I'm getting a "Cannot read property 'findIndex' of undefined" error. It seems 'carouselEl.current.state.clones' isn't being found.

**Comment by YIZHUANG** [comment]
Looks like some changes in the newer version broke this, I will look into it and provide a better solution to do this.

**Comment by YIZHUANG** [comment]
```
import {getClones} from 'react-multi-carousel/lib/utils/clones';
const childrenArr = React.children.toArray(carouselEl.current.props.children);
const slidesToShow = carouselEl.current.state.slidesToShow;
const clones = getClones(slidesToShow,childrenArr);
```

You can use this as a temporarily workaround

**Comment by YIZHUANG** [comment]
@chocobuckle Can you tell a little bit about your use case? I need to think about if supporting these kind of logic is within the scope of this component.
