### ISSUE TITLE
bug when dynamicly changing keyBoardControl prop

### ISSUE THREAD

**Issue by waxyfoxy** [YIZHUANG/react-multi-carousel#53]
**Describe the bug**
I change the value of the keyboardControl prop when a modal or a sidebar is open to prevent arrow use to slide the carousel. When the value goes to false the carousel stop sliding when arrows are hit however, when the value goes back to true, arrows don't slide the carousel anymore

**To Reproduce**

const modalOpen = contextPanelProps.children != null || omniboxProps.open
keyBoardControl={!modalOpen}

**Expected behavior**
the carousel should handle changing value for the keyboardControl prop

**Comment by YIZHUANG** [comment]
Hi, thank you for reporting this, feel free to open up a pr to fix this, should be faily easy in the componentDidUpdate and componentWillUnMount method.

**Comment by YIZHUANG** [comment]
this is fixed in https://github.com/YIZHUANG/react-multi-carousel/commit/ecd4f2500c69202d9a72bec5847e85de452be7fa.

Do:
```
npm install react-multi-carousel --latest --save
```
