### ISSUE TITLE
scroll animation effect missing when completing a turn in infinite mode

### ISSUE THREAD

**Issue by waxyfoxy** [YIZHUANG/react-multi-carousel#57]
**Describe the bug**
Hello Yi, there is a scroll animation missing when you complete a turn of the carousel in infinite mode. Are you aware of this bug ? 

**To Reproduce**
create a carousel with only a few items, enable infinite mode and try completing a full turn.

**Expected behavior**
Animation effect should always be the same

**Comment by YIZHUANG** [comment]
Hi, thank you for the report, is there a code sandbox or some code snippets?

**Comment by waxyfoxy** [comment]
Hi Yi, my bad I had the prop "transitionDuration" set to 0 which caused this no-effect. Problem solved. Thanks for your quick answer though and thanks again for your great job !
