### ISSUE TITLE
Slider is Overflowing and calculating wrong width for the <li>

### ISSUE THREAD

**Issue by anupchrome** [YIZHUANG/react-multi-carousel#59]
**Describe the bug**
Slider is Overflowing and calculating wrong width for the LI Tag on the run time

**To Reproduce**
I m not sure how to reproduce because it was working and then the other day it stopped working.

**Screenshots**
It was suppose to look like this :
https://imgur.com/a/Km77sFc
But it's looking like this now:
https://imgur.com/a/5dDyGZP (Look at the width of the LI element in the inspect element)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Comment by anupchrome** [comment]
I think I solved it by wrapping the whole carousel into a container (Bootstrap Class) Div.
Previously it was in row class (Bootstrap Class) Div.
Thanks

**Comment by YIZHUANG** [comment]
Hi, do you have a minimum code sandbox reproduction that I can see?

**Comment by anupchrome** [comment]
> Hi, do you have a minimum reproduction on code sandbox or just code snippets that I can see?

I did not modified anything in the code it was just straight copy paste from the documentation.
But here's what I did to fix the problem for mobile. I wrapped it up into a container and for mobile I wrote this CSS which seems to solve the problem for unknown reason:
`@media(min-width:480px){
    .container{
        max-width: 440px;
    }
}
@media(min-width:360px){
    .container{
        max-width: 320px;
    }
}`
This caused my whole project's layout damage, which my client told me the next day.

I created a TextSlider component and imported it into my page:
Here's the Testing URL : http://ec2-13-233-173-113.ap-south-1.compute.amazonaws.com:3000/succeed-together

If you go into inspect element and remove the CSS which I mentioned above, you'll see the problem.

This is my .tsx file code:
`import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
import "./Text-Slider.scss";

const responsive = {
    superLargeDesktop: {
      breakpoint: { max: 4000, min: 3000 },
      items: 5,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
    },
    tablet: {
      breakpoint: { max: 1024, min: 600 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 600, min: 0 },
      items: 1,
    },
  };

function TextSlider(props){
    
    let SliderArray = props.SliderArray;

    const SliderDetails = SliderArray.map((SliderArray) =>
        <div className="single-slide">
            <h4>{SliderArray.slideTitle}</h4>
            <p>{SliderArray.slideDesc}</p>
        </div>
    )

    return(
        <div className="text-slider-wrapper">

            <Carousel arrows={false} responsive={responsive} showDots={true} dotListClass="custom-indicator">

                {SliderDetails}

            </Carousel>
            
        </div>
        
    )
}
export default TextSlider`

**Comment by YIZHUANG** [comment]
@anupchrome   
<img width="857" alt="Screenshot 2019-09-10 at 19 49 47" src="https://user-images.githubusercontent.com/28932103/64633601-2c516400-d404-11e9-81e3-351259698453.png">

Uncheck the display: "flex"

**Comment by anupchrome** [comment]
Thank you.
I'll keep that in mind in future.
