### ISSUE TITLE
is this production ready

### ISSUE THREAD

**Issue by andrew-oko-odion** [YIZHUANG/react-multi-carousel#6]
Is this carousel production ready yet? 

I like it and would like to contribute...

**Comment by YIZHUANG** [comment]
Hi, yes!
It is already used in one of the largest companies' website in Nordic, but due to confidentiality I can't tell which.
You are more than welcome to contribute as this is needed very much😊😊.

**Comment by andrew-oko-odion** [comment]
Happy  to hear that its production ready
would definitely contribute to this.
Thanks again.

**Comment by YIZHUANG** [comment]
@andrew-oko-odion  Hi, i added a contributing guide. https://github.com/YIZHUANG/react-multi-carousel/blob/master/contributing.md
