### ISSUE TITLE
Warning: React does not recognize the `carouselState` prop on a DOM element.

### ISSUE THREAD

**Issue by AlexeyFominykh** [YIZHUANG/react-multi-carousel#61]
**Describe the bug**
with customLeftArrow warning in console:
Warning: React does not recognize the `carouselState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `carouselstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**To Reproduce**
use customLeftArrow prop <Carousel customLeftArrow={...}

**Comment by YIZHUANG** [comment]
Hi,


More code snippets? It's hard to see from here.

**Comment by AlexeyFominykh** [comment]
hi, just use any customLeftArrow like customLeftArrow={<span>123</span>}

i can resolve it locally by hack like:
const ArrowFix = (arrowProps) => {
            const {carouselState, children, ...restArrowProps} = arrowProps; // to delete carouselState prop
            return (
                <span {...restArrowProps}>
                    {children}
                </span>
            );
        };

customLeftArrow={<ArrowFix>123</ArrowFix>} - it works

**Comment by YIZHUANG** [comment]
Yeah, this is how you should use it.

**Comment by wilsonibekason** [comment]
i don't still understand can you write it in full
