### ISSUE TITLE
No pause on hover support

### ISSUE THREAD

**Issue by Alchy-web** [YIZHUANG/react-multi-carousel#73]
There is no option to pause the carousel on hover.

Can you add a prop pauseOnHover (pauseOnHover={true})

**Comment by YIZHUANG** [comment]
You mean autoPlay? This is enabled by default.

**Comment by eladams** [comment]
Applying the following props: 
``` jsx
<Carousel 
    infinite
    autoPlaySpeed={1}
    autoPlay
    customTransition={"all 40s linear"}
    transitionDuration={40000}
>
        {...items}
</Carousel>
```

Will wait 40 sec until it pauses. What if we want it to stop immediately?

**Comment by NikkiJonesR** [comment]
@eladams I'm running into the same issue, were you able to disable this somehow? @YIZHUANG this would be a nice feature to have, otherwise I'll have to use a different library.

**Comment by ahmetuysal** [comment]
@eladams @NikkiJonesR did you manage to find a way to pause immediately? I am having the same issue :/

**Comment by eladams** [comment]
No, sorry. I guess if I still needed it I would fork this as it is not responded for such a long time and the count of pull requests is currently on 28 :)
