### ISSUE TITLE
Arrows not showing in dynamic items

### ISSUE THREAD

**Issue by mnksingh** [YIZHUANG/react-multi-carousel#77]
I am using a carousel to render interest in a a carousel and the user can add or remove items.
Currently my responsive object is as follows: 

```
const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 900 },
    items: 5,
  },
  tablet: {
    breakpoint: { max: 900, min: 600 },
    items: 3,
  },
  mobile: {
    breakpoint: { max: 600, min: 0 },
    items: 1.2,
    partialVisbile: true,
    partialVisibilityGutter: 30,
    arrows: false,
  },
};
```

Now the issue is if my carousel has more than 5 five items when loading the carousel it is rendering the arrows. But when I am less items for example 2 and then I add 4 items to make it 6  then it is not showing arrows.

**Comment by YIZHUANG** [comment]
Can you provide a codesandbox reproduce?
