### ISSUE TITLE
React memory leak

### ISSUE THREAD

**Issue by sT0pe** [YIZHUANG/react-multi-carousel#87]
**Describe the bug**
"Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."

If unmount carousel (change page route, ext.) strait away after component loads.

could you please fix this issue. Maybe it is bcs of setItemsToShow function in timeout

**Comment by YIZHUANG** [comment]
This is a normal behavior.

**Comment by rlundquist3** [comment]
@sT0pe see #198

**Comment by rlundquist3** [comment]
@YIZHUANG yes this would be expected, but the problem can be resolved by clearing timeouts on unmount (see linked PR)

**Comment by juanisimioli** [comment]
Hi! How can apply these changes from PR #198 to my Carousel? I tried to find the file src/Carousel.tsx in my node_modules folder, but I couldn't find it.
Thanks!
