### ISSUE TITLE
Last slide is invisible if swiping to the right but not to the left

### ISSUE THREAD

**Issue by mfgabriel92** [YIZHUANG/react-multi-carousel#90]
**Describe the bug**
I have a small infinite slider containing only texts. It holds an `h1` and `h2` within a few `div`s. When clicking to left it will loop normally showing all items, but when clicking on the right, for some reason, when reaching the last item, it will be invisible.

**Screenshots**
![Peek 2019-10-21 10-44](https://user-images.githubusercontent.com/26734503/67211178-b112a300-f3f0-11e9-965b-c0890b7f5f29.gif)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Browser: Chrome
 - Version: 77.0

**Additional context**
It is a small block holding the slider, not 100% width. I don't know if it should be of any issue.

**Comment by YIZHUANG** [comment]
Hi, any code snippets?
