### ISSUE TITLE
`partialVisbile` property is spelt wrong

### ISSUE THREAD

**Issue by Dan503** [YIZHUANG/react-multi-carousel#92]
The `partialVisbile` property on the `<Carousel>` component should be spelt `partialVisible` (swap the "b" and the "i" around).

Unfortunately this is also a breaking change :(

**Comment by abhinavdalal-iconnect** [comment]
@YIZHUANG @Dan503  my PR to fix the typo keeping backwards compatibility :
https://github.com/YIZHUANG/react-multi-carousel/pull/93
