### ISSUE TITLE
Is it possible to extract font files?

### ISSUE THREAD

**Issue by damianmalinowski** [YIZHUANG/react-multi-carousel#94]
Would it be possible to extract font files from style.css ? 
I am just thinking about start using your library but I don't want to add additional files with fonts to my solution.

If I see correctly carousel uses just buttons icons from included fonts?

Thanks for good looking carousel :)

**Comment by YIZHUANG** [comment]
Hi, you can just copy paste the Css code to your own and exclude the font import.
