### ISSUE TITLE
Is it possible to jump to a specific slide?

### ISSUE THREAD

**Issue by alex-windett** [YIZHUANG/react-multi-carousel#96]
Is it possible to jump to a specific slide without interacting with either a Dot, Arrow or Slide? In other words from outside the Carousel component.

for example 

```jsx

import Carousel from 'react-multi-carousel'

const MyCarousel = () => {

  const [activeSlide, setActiveSlide] = useState(0)
  
  const  goToSlide = (slideNumber) => setActiveSlide(slideNumber)

  return (
    <>
     <button type="button" onClick={goToSlide(3)}>Jump to Slide 3</button>

     <Carousel activeSlide={activeSlide}>
       <p>item 1</p>
       <p>item 3</p>
       <p>item 2</p>
       <p>item 4</p>
     </Carousel>
   </>
  )
}
```

Does not have to use hooks syntax

**Comment by macsplan** [comment]
Same here i'm trying to get around the same problem

**Comment by YIZHUANG** [comment]
It's in the documentation.

**Comment by abhinavdalal-iconnect** [comment]
@alex-windett @macsplan  hope this helps: 

`<Carousel ref={(el) => (this.Carousel = el)}>
  <ItemOne />
  <ItemTwo />
</Carousel>

const myCustomGoToSlide = (nextSlide) => this.Carousel.goToSlide(nextSlide);
`

**Comment by alex-windett** [comment]
@abhinavdalal-iconnect  Just what i was after. Thank you

**Comment by macsplan** [comment]
Im still trying to implement this i spent all day trying to make it work but the carousel refuses to move even though the data is all passed correctly

 import React, { useState, useEffect, useRef } from 'react';
import Carousel from "react-multi-carousel";
import Modal from './Modal.js';
import "react-multi-carousel/lib/styles.css";

const Gallery = props => {
  const carouselRef = useRef()
  const [data, setData] = useState(props.data);
  const [currentselected, updateSelected] = useState(props.currentData.id);
  const [selected, update] = useState("");

  const handleClick = (e, item) => {
    props.passClick(item)
    updateSelected(item.id)
    update(item.id)
  }

  const activeIndex = 3;

  useEffect(() => {
    console.log('useEffect', carouselRef, carouselRef.current, activeIndex)
    if (carouselRef && carouselRef.current) {
      carouselRef.current.goToSlide(currentselected);
    }
  }, [carouselRef]);


  return (
    <div className="flex items-center relative product-carousel px-12">
      <Carousel
        ref={carouselRef}
        ssr={false}
        swipeable={true}
        draggable={true}
        showDots={false}
        infinite
        responsive={{
          desktop: {
            breakpoint: {
              max: 3000,
              min: 960
            },
            items: 3
          },
          mobile: {
            breakpoint: {
              max: 464,
              min: 0
            },
            items: 1
          },
          tablet: {
            breakpoint: {
              max: 959,
              min: 464
            },
            items: 2
          }
        }}
        additionalTransfrom={0}
        arrows
        autoPlaySpeed={3000}
        centerMode={false}
        className=""
        containerClass="container-with-dots"
        dotListClass=""
        draggable
        itemClass=""
        keyBoardControl
        minimumTouchDrag={80}
        renderButtonGroupOutside={false}
        renderDotsOutside={false}
        >
        {props.currentLocation === "/hidden-away-stories" &&
          <React.Fragment>
          <button aria-label={`button to open map`} className="item"  key="mapid" onClick={props.toggleMapview}
          >
          <img src="/contributors/map.jpg" className="image"/>
          <img src="/contributors/map_hover.jpg" className="hoverOverlay"/>
          </button>
          </React.Fragment>
        }

        { data.map((item, index) => {
          return (
          <React.Fragment key={item.id}>
            <Modal data={item} />
            <button
              aria-label={`button to open ${item.title} popup`}
              className={`item ${selected === item.id ? 'selected' : ""}`}
              key={item.id}
              onClick={(e, props) => handleClick(e, item)}>
             <img src={item.img} className="image" aria-label={`Phote of interview subject ${item.alt}`}/>
             <img src={item.hover} className="hoverOverlay"/>
            </button>
          </React.Fragment>
          )
        })}
      </Carousel>
    </div>
  )
}

export default Gallery

**Comment by abhinavdalal-iconnect** [comment]
@macsplan i think your useEffect is incorrect; your effect will run whenever `carouselRef` changes..

I think what your intention is that your effect run whenever props.currentData.id changes; so you can probably try:

```  useEffect(() => {
    console.log('useEffect', carouselRef, carouselRef.current, activeIndex)
    if (carouselRef && carouselRef.current) {
      carouselRef.current.goToSlide(currentselected);
    }
  }, [props.currentData.id]);
```

**Comment by vengadesh-m** [comment]
While the Carousel is loaded, is it possible to go to a particular slide rather than the first slide?
