### ISSUE TITLE
The carousle component does not render slides correctly.

### ISSUE THREAD

**Issue by damianmalinowski** [YIZHUANG/react-multi-carousel#97]
**Describe the bug**
The carousel component does not render slides correctly when you provide children after the carousel constructor was called.
I suspect that is caused by calculating the total items in the constructor.

**Screenshots**
![image](https://user-images.githubusercontent.com/18700400/67765398-59a5b000-fa4c-11e9-819c-c8d37d51067b.png)

**Desktop (please complete the following information):**
 - Chrome 

**Reproduction**
Link to codesandbox: 
https://codesandbox.io/s/focused-joliot-w09ji?fontsize=14

**Comment by abhinavdalal-iconnect** [comment]
@damianmalinowski @YIZHUANG this will be addressed by https://github.com/YIZHUANG/react-multi-carousel/pull/71

we now detect change in props in the componentDidUpdate and call the necessary functions..

**Comment by YIZHUANG** [comment]
Why not only render the Carousel after you have children to provide?

**Comment by YIZHUANG** [comment]
It's now in 2.4.1
