### ISSUE TITLE
The carousel breaks if it is a flexbox flex item

### ISSUE THREAD

**Issue by Dan503** [YIZHUANG/react-multi-carousel#98]
**Describe the bug**
The following will completely break the carousel. The carousel will simply not be visible.

```css
.flexbox-container {
    display: flex;
}
```
```html
<div className="flexbox-container">
    <Carousel>
        <Item/>
        <Item/>
        <Item/>
        <Item/>
    </Carousel>
</div>
```

**Expected behavior**
The carousel should work just as well as a flexbox or CSS Grid item as it does in a regular unstyled div element.

**Browser:**

I think this is a common issue across all browsers and devices.

**suggestion**

I was able to get it to display by doing this:

```html
<div className="flexbox-container">
  <div style={{width: '100%'}}>
    <Carousel>
        <Item/>
        <Item/>
        <Item/>
        <Item/>
    </Carousel>
  </div>
</div>
```

But I wanted to create custom controls that were flex-children of the `flexbox-container` element. That wasn't possible with this flexbox bug.

I suggest adding an extra wrapper div with 100% width around the carousel portion as a buffer between flexbox and the carousel.

**Comment by ranausama48** [comment]
if we add 
    flex-wrap: wrap;
property to
 .flexbox-container {
    display: flex;
}
then it is worked

**Comment by florianGierlichs** [comment]
I tried with flex-direction: column;
Unfortunately, this didn't work.

**Comment by alexandraturian** [comment]
For me, the carousel renders if I use `display: flex; flex-direction: column;`
But with `flex-direction: row`, which I want, does not work

**Comment by alexandraturian** [comment]
@florianGierlichs  it also works well with `display: grid`

**Comment by GHesericsu** [comment]
I have the same issue with displaying carousel inside flex display

**Comment by wonderfulxue** [comment]
Have the same issue here. Carousel completely crash if it was placed in a flex container

**Comment by Alileus** [comment]
Add it inside a div with overflow: hidden

**Comment by SaadBazaz** [comment]
Still happens. Had to resort to ```display:grid```. A lot of libraries use flex deep inside their implementation...

**Comment by qiangkaiwen** [comment]
I have a same issue, I am using MUI Grid component so Grid is wrapping the Carousel. In this case, it is not displaying the carousel in mobile phone and css not applied to the carouse on desktop.

**Comment by tiennsloit** [comment]
For me, it works again if the width of the closet div is full width (100%) or a specific px:
<div className="flex">
  <div className="w-full">
          <Carousel>
           <div>Item 1</div>
            <div>Item 2</div>
            <div>Item 3</div>
         </Carousel>
</div>

**Comment by YIZHUANG** [comment]
Hello, the parent's width needs to be set to 100%

**Comment by dvenomb98** [comment]
<div className="page-layout flex flex-col gap-2 items-center">
        {header && <h2 className="h2">{header}</h2>}
        {subheader && <RichParagraph text={subheader} />}
      
      <Carousel
        className="py-4 w-full"
        .....
        
w-full worked me without unnecessary div.

**Comment by AbdulWajid768** [comment]
Wrap the `Carousel` inside `div` and play with `max_width` and `max_height` to `div`. The following solution worked for me.

```css
.roller2 {
  max-width: 25rem;
}
``` 

```javascript
<div className={styles.roller2}>
  <Carousel showArrows={false} showIndicators={false} showStatus={false} infiniteLoop={true} dynamicHeight={false}
            autoPlay={true} autoFocus={true} swipeable={true} useKeyboardArrows={true} emulateTouch={true}>
    {reviews.map((review, index) => <Review key={index} name={review.name} text={review.text}
                                            rating={review.rating}/>)}
  </Carousel>
</div>
```
