### ISSUE TITLE
How to get the slide index with afterChange in infinite-mode?

### ISSUE THREAD

**Issue by henrik-d** [YIZHUANG/react-multi-carousel#99]
Hi,
I'm having problems with getting the current slide index in `afterChange` in infinite-mode. I know this is happening due to the slide clones.

```
const afterChange = () => {
        if (carouselRef.current) {
            const slide = carouselRef.current.state.currentSlide;
            // slide is 2, 3, 4
            // expecting 0, 1, 2
        }
    };
```
How can I get the index of the slide?

Thanks!

**Comment by abhinavdalal-iconnect** [comment]
@henrik-d there is a function for this `getOriginalCounterPart`
so you may need to do
```

const slide = carouselRef.current.getOriginalCounterPart(
  0,
  carouselRef.current.state.slidesToShow,
  carouselRef.current.state.currentSlide
);
```

**Comment by YIZHUANG** [comment]
@abhinavdalal-iconnect is correct

**Comment by henrik-d** [comment]
From my understanding `getOriginalCounterPart()` calculated the "clonedIndex" from a "realIndex". My problem was vise-vera. I wanted to select the nth child of my children. I don't know if this code covers every usecase, but it works for me:

```
let realIndex = state.currentSlide - 2 * state.slidesToShow;
if (current < 0) {
    const numberOfSlides = React.Children.count(carousel.current.props.children);
    realIndex = numberOfSlides + current;
}
```
